### ISSUE TITLE
Brute force protection for admin

### ISSUE THREAD

**Issue by ishitatsuyuki** [maxking/docker-mailman#100]
See: https://stackoverflow.com/a/45328687/2484972

**Comment by maxking** [comment]
This should be added to the django-mailman3 package and not be a part of packaging.

**Comment by maxking** [comment]
Can you open a issue at http://gitlab.com/mailman/django-mailman3

**Comment by ishitatsuyuki** [comment]
Opened as https://gitlab.com/mailman/django-mailman3/issues/6. I recommend keeping this open as a reminder to backport when upstream address it.

**Comment by maxking** [comment]
Sure, thanks!
