### ISSUE TITLE
Containers should be able to run with read-only root

### ISSUE THREAD

**Issue by ishitatsuyuki** [maxking/docker-mailman#105]
Things found so far:

```
mailman-core    | /opt/run.sh: line 26: /etc/mailman.cfg: Read-only file system
mailman-web     | cp: can't create '/opt/mailman-web/settings_local.py': Read-only file system
```

**Comment by maxking** [comment]
I am not much aware about the concept of read-only root in containers, are they common practice? Also what are the locations that can be written to in a read-only root? Only the external mounted locations/volumes?

**Comment by ishitatsuyuki** [comment]
For the first question, it's highly preferred because any non-volume write triggers CoW and results in very poor IO.

For the second questions, yes, mounts only.

**Comment by maxking** [comment]
CoW does have very bad performance in case of large files, but I can't imagine any noticeable performance hit writing small configuration file during startup.

**Comment by ishitatsuyuki** [comment]
If my understanding is correct, it will result in the full image being copied.

**Comment by maxking** [comment]
Full image being copied to where?

Writes to the rootfs just copies the file being written to from base layer to the top writable layer, which in this case is a new file so no copying either, and modifies the contents of that file.

**Comment by ishitatsuyuki** [comment]
Uh no it isn't. But in real scenes, I'm aware that layered filesystems generally imposes huge overhead if you created additional layers.

**Comment by maxking** [comment]
But new layers aren't created at all, all changes happen on one single writeable layer on the top.

**Comment by ishitatsuyuki** [comment]
As it doesn't pose any runtime overhead and writing to rootfs is seen in a number of official Docker images, I'm closing this.
