### ISSUE TITLE
Add instructions for social login

### ISSUE THREAD

**Issue by maxking** [maxking/docker-mailman#11]
https://django-allauth.readthedocs.io/en/latest/installation.html#post-installation

Django allauth requires some setup before it starts working. It needs to be setup using the django's admin console. The process isn't very difficult but needs to be documented somewhere so that people don't expect it to work out of the box.

**Comment by ulrith** [comment]
Yes, it would be very useful to have this documented.
After `docker-compose up`, If I open /admin/ page what user credentials should I use?
Has `django createsuperuser` already run on this stage?

**Comment by ulrith** [comment]
The answer seems 'No'. Here is a command for creation of superuser after containers are up:

docker-compose exec -T mailman-web bash -c "echo \"from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'admin@site.com', 'password')\" | python manage.py shell"

**Comment by maxking** [comment]
@ulrith you can create one like this too:
```
docker-compose exec -T mailman-web python manage.py createsuperuser
```
This command is going to be interactive but will work.

I will add it to documentation. Thanks!

**Comment by ulrith** [comment]
Yes, thanks, and my command listed above is non-interactive and it works too :)

**Comment by maxking** [comment]
@ulrith Also, getting social logins to work is a little tricky if you are doing it for the first time, let me know and I can help you get started.

**Comment by ulrith** [comment]
@maxking I'd like to accept your offer to configure social logins now :)

**Comment by maxking** [comment]
@ulrith Sure! We should move to IRC or email?

**Comment by ulrith** [comment]
@maxking Yes thanks! I've sent an email to you

**Comment by almereyda** [comment]
This would also include instructions about how to disable social login via a custom `settings_local.py`.

**Comment by maxking** [comment]
@almereyda It should not be very difficult to just remove all the social logins. You just change the INSTALLED_APPS to remove all the social logins.

There potentially could be an environment variable to disable it if enough people are interested to get rid of social logins by default, but for now, changing the INSTALLED_APPS in django's `settings_local.py` would be what I would suggest.

**Comment by Dragnell87** [comment]
@maxking  Hi, i tried what you suggested but it didn't not work, there is any other way to disable the external sign in from social networks in HyperKitty  ?

**Comment by Dragnell87** [comment]
OK i found the solution, is as you said but, you cannot delete or comment allauth.socialaccount otherwise the migration at start up will fail.

**Comment by maxking** [comment]
@Dragnell87 Yeah that would make sense because that is the only app which uses database. 

Although, you *might* be able to get rid of that if you use a fresh copy of database. Since migrations are expected to be generated by the apps, the migrate command would be expected to fail in case a table disappers without a migration.

`python mange.py makemigrations && python manage.py migrate` might work, but would have to be done on each restart.
