### ISSUE TITLE
Postfix configuration is not generated

### ISSUE THREAD

**Issue by Dragnell87** [maxking/docker-mailman#118]
According to DOC The configuration file /etc/postfix-mailman.cfg is generated automatically. But i can't  find it anywhere in the system. Not sure if related but at the time i can deliver mail to any list.

Recipient address rejected: User unknown in virtual
    mailbox table (in reply to RCPT TO command)

**Comment by maxking** [comment]
It is generated inside the `mailman-core` container and you won't see it on your system.

Can you show me the relevant postfix configuration? It would help to understand what is going on.

The transport maps are usually stored at `/opt/mailman/core/var/data` on the host filesystem.

**Comment by Dragnell87** [comment]
Sure,
postfix_domains : 
# AUTOMATICALLY GENERATED BY MAILMAN ON 2017-08-07 18:22:59
#
# This file is generated by Mailman, and is kept in sync with the binary hash
# file.  YOU SHOULD NOT MANUALLY EDIT THIS FILE unless you know what you're
# doing, and can keep the two files properly in sync.  If you screw it up,
# you're on your own.

/^cubava\.cu$/ cubava.cu
/^jovenclub\.cu$/ jovenclub.cu

 postfix_lmtp : # AUTOMATICALLY GENERATED BY MAILMAN ON 2017-08-07 18:22:59
#
# This file is generated by Mailman, and is kept in sync with the binary hash
# file.  YOU SHOULD NOT MANUALLY EDIT THIS FILE unless you know what you're
# doing, and can keep the two files properly in sync.  If you screw it up,
# you're on your own.
    
# Aliases which are visible only in the @cubava.cu domain.
/^filiales\.scjm@cubava\.cu$/               lmtp:[172.19.199.2]:8024
/^filiales\.scjm-bounces@cubava\.cu$/       lmtp:[172.19.199.2]:8024
/^filiales\.scjm-confirm@cubava\.cu$/       lmtp:[172.19.199.2]:8024
/^filiales\.scjm-join@cubava\.cu$/          lmtp:[172.19.199.2]:8024
/^filiales\.scjm-leave@cubava\.cu$/         lmtp:[172.19.199.2]:8024
/^filiales\.scjm-owner@cubava\.cu$/         lmtp:[172.19.199.2]:8024
/^filiales\.scjm-request@cubava\.cu$/       lmtp:[172.19.199.2]:8024
/^filiales\.scjm-subscribe@cubava\.cu$/     lmtp:[172.19.199.2]:8024
/^filiales\.scjm-unsubscribe@cubava\.cu$/   lmtp:[172.19.199.2]:8024

/^todos\.scjm@cubava\.cu$/               lmtp:[172.19.199.2]:8024
/^todos\.scjm-bounces@cubava\.cu$/       lmtp:[172.19.199.2]:8024
/^todos\.scjm-confirm@cubava\.cu$/       lmtp:[172.19.199.2]:8024
/^todos\.scjm-join@cubava\.cu$/          lmtp:[172.19.199.2]:8024
/^todos\.scjm-leave@cubava\.cu$/         lmtp:[172.19.199.2]:8024
/^todos\.scjm-owner@cubava\.cu$/         lmtp:[172.19.199.2]:8024
/^todos\.scjm-request@cubava\.cu$/       lmtp:[172.19.199.2]:8024
/^todos\.scjm-subscribe@cubava\.cu$/     lmtp:[172.19.199.2]:8024
/^todos\.scjm-unsubscribe@cubava\.cu$/   lmtp:[172.19.199.2]:8024

Those are tho only files under /opt/mailman/core/var/data/

Thanks for your time

**Comment by maxking** [comment]
This looks correct, what about your configuration in postfix? /etc/postfix/main.cfg?

**Comment by Dragnell87** [comment]
Hi, here it is. 
https://paste.ubuntu.com/25325581/

**Comment by maxking** [comment]
```
transport_maps = regexp:/opt/mailman/core/var/data/postfix_lmtp
local_recipient_maps = regexp:/opt/mailman/core/var/data/postfix_lmtp
relay_domains = regexp:/opt/mailman/core/var/data/postfix_domains
```

This is the relevant portion for Mailman3 and it seems to be actually correct. I am not sure about the reason why Postfix doesn't accept the emails for these addresses. 

It *looks* like postfix only checks with Dovecot for the user's mailbox and hence rejecting the emails for mailman. Someone with more postfix knowledge might be able to help better than me.

**Comment by Dragnell87** [comment]
Ok, if i found out anything i will come back, about the postfix-mailman.cfg that is generated, how should the content looks like, and where in the docker container should it be?

**Comment by thorthor68** [comment]
I also cannot find the postfix-mailman.cfg anywhere.

**Comment by maxking** [comment]
https://github.com/maxking/docker-mailman/blob/master/core/docker-entrypoint.sh#L105

It should be at `/etc/postfix-mailman.cfg` in mailman-core container.

**Comment by maxking** [comment]
Closing this issue, please re-open if you think there is still a problem.
