### ISSUE TITLE
Mailman sending out wrong smtp headers.

### ISSUE THREAD

**Issue by thorthor68** [maxking/docker-mailman#126]
I get this in postfix /var/log/mail.log:

(on external server):
warning: Illegal address syntax from host.compute.amazonaws.com[52.29.xx.xx] in RCPT command: <>

(same thing on docker host):
warning: Illegal address syntax from mailman[172.19.199.2] in RCPT command: <>

When trying to reproduce it manually by doing telnet <host> 25, it seems that postfix is expecting to see [From:] and/or [To:] headers within the DATA section, while mailman only issues MAIL FROM and RCPT TO.
[mailman-log-smtp.txt](https://github.com/maxking/docker-mailman/files/1327617/mailman-log-smtp.txt)
[postfix-log.txt](https://github.com/maxking/docker-mailman/files/1327650/postfix-log.txt)

So it seems that Mailman produces a response to at least some incoming messages, but they are stopped because of malformed headers.

Apart from that, I also have problem when creating a new discussion in or replying to messages in Hyperkitty. It says the message is sent, but nothing appear in smtp/postfix logs. Messages do come in to Hyperkitty.

**Comment by maxking** [comment]
It looks like an issue with Mailman Core and not container images. Can you please open an issue at https://gitlab.com/mailman/mailman/issues ?

**Comment by maxking** [comment]
Closing this one, please re-open if you find this to be a problem with images instead of Core itself.
