### ISSUE TITLE
Feature request: redirect log /opt/mailman/var/logs/mailman.log to stdout in mailman-web container

### ISSUE THREAD

**Issue by ghost** [maxking/docker-mailman#134]
It would be nice if `/opt/mailman/var/logs/mailman.log` could be logged to stdout in mailman-web. This would help a lot for noticing issues like e.g. the hyperkitty api key being wrong or MAILMAN_HOST_IP being set incorrectly, preventing archiving and other issues which may yield to warnings/errors in that log.

Maybe the django logger could be set to `/dev/stdout` by the docker-mailman scripts or something similar?

**Comment by maxking** [comment]
I wonder if it would work if you just the `DJANGO_LOG_URL` to `/dev/stdout`.

In theory it should, not sure about it though. Ideally, "console" handler logs to stdout.
