### ISSUE TITLE
Example docker-compose.yml uses absolute paths for volumes

### ISSUE THREAD

**Issue by ghost** [maxking/docker-mailman#135]
The example docker-compose.yml uses absolute host paths for volumes:
`/opt/mailman/core` and `/opt/mailman/database`

This will lead to conflicts and errors when people want to set up multiple mailman docker-compose groups on their server in separate folders (which, apart from this, would be easily possible) and also goes against the spirit of docker-compose to keep all relevant files in the local folder.

Therefore, I suggest those host paths for the volumes instead:
- `./volumes/opt-mailman-core/`
- `./volumes/opt-mailman-database/`

(and yes docker-compose supports `./` at the beginning of volume paths, unlike the `docker` command line tool itself which requires absolute paths since it has no such concept of a local folder containing all required resources)

**Comment by ishitatsuyuki** [comment]
I just use named volumes, and separate the volumes that needs to be shared to postfix or nginx.

**Comment by JonasT** [comment]
Yes but named volumes won't be contained inside the docker-compose folder (similar to the absolute paths currently used) so they're harder to backup and therefore less beginner friendly. Relative paths is really the best no-brainer default setup for new people, and everyone else can easily reconfigure it - I already did for myself as well, I just want to suggest a better default here.
