### ISSUE TITLE
Provide a pre-compiled tarball for all static contents

### ISSUE THREAD

**Issue by maxking** [maxking/docker-mailman#144]
This is basically just a thought.

If I can provide a tarball of all the static content, it is possible to make mailman-web container entirely state-less with no-need to mount anything as static files are the only thing thing that need to be shared with web server. Static files could be compiled per-release and stored along with releases on Github?

It is also possible to configure uwsgi to serve static files and if the performance is *good enough*, we can let go of mounting directory method.

**Comment by ishitatsuyuki** [comment]
What's the point of prepackaging the static files? Generating them is fast enough. With mounts update is seamless.

I prefer delegating static files to my front nginx, but anyway it's just a matter of preference.

**Comment by maxking** [comment]
Yeah, I often find people questioning about missing static files.

`uwsgi` has an option to serve static files, maybe they can be configured properly using environment variables. This issue is just meant to explore options :)
