### ISSUE TITLE
Better nginx configuration using the uwsgi_pass instead of the proxy_pass

### ISSUE THREAD

**Issue by maxking** [maxking/docker-mailman#15]
uwsgi has a native support in nginx, why not just use that instead of using proxy_pass?

http://uwsgi-docs.readthedocs.io/en/latest/Nginx.html

Update the documentation and the nginx configuration to do so.

**Comment by almereyda** [comment]
I cannot find nginx configuration in this repository.
Is this maybe strongly related with #64?

**Comment by maxking** [comment]
@almereyda The [README](https://github.com/maxking/docker-mailman#setting-up-your-web-server) for the project has information about how to setup nginx.

This issue should actually be related-to #64 though, my bad.
