### ISSUE TITLE
mailman-core fails to start due to stale master.lck

### ISSUE THREAD

**Issue by droopy4096** [maxking/docker-mailman#159]
Every once in a while I get mailman-core leaving master.lck behind which results in a startup failure for mailman-core container. Perhaps adding code removing the lock inside the container could solve the issue.

**Comment by maxking** [comment]
I agree and have been thinking about fixing this since some time now. I will probably end up fixing this soon.

As a workaround, you can specify the command to run with mailman-core as `master --force` and it will take care of this.

**Comment by droopy4096** [comment]
this doesn't work as command comes into play at the end of docker-entrypoint.sh whereas check for .lck presence is done in first lines. :(

**Comment by maxking** [comment]
Ah! That makes sense. I think we should just remove that check completely.

Ideally, I would like some way to let Core die properly and not have to send SIGKILL to it, but Docker doesn't really specify a clean way to do that. After 10 seconds of SIGTERM, it will just kill the process leaving the master.lck behind.

**Comment by droopy4096** [comment]
composer has "stop_signal" and "stop_grace_period" that should take care of it, no?

**Comment by maxking** [comment]
I knew about "stop_signal", but I didn't know about "stop_grace_period", thanks! That should help a lot with graceful shutdown of mailman-core container I believe.

I will add that and remove check for master.lck .

**Comment by ishitatsuyuki** [comment]
Failing restarts are really a burden. Normally frameworks has some grade of consistency built in, like SQL transactions.

I also suggest toward removing the lockfile.
