### ISSUE TITLE
mailman-web refuses to start

### ISSUE THREAD

**Issue by fsantiago07044** [maxking/docker-mailman#160]
hello,

i just cloned the git and i believe i configured everything necessary:

the yaml file
settings.py under /web

when i bring it up with docker-compose, the mailman-web portion doesn't seem to start. at least i cannot ping the .3 address. docker-compose does not seem to complain. where could i look for addt'l info on this? Thanks.

i can ping the other addresses. i'm stuck.

**Comment by maxking** [comment]
`docker logs mailman-web` could be helpful!

**Comment by fsantiago07044** [comment]
October 23, 2017 3:38 PM, "Abhilash Raj" <notifications@github.com> wrote:

> docker logs mailman-web could be helpful!
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

there are no mailman-web logs anywhere on my system. 

i can see mailman-core logs though. the folder /opt/mailman/web is empty. 

i cloned the git into /usr/src/docker-mailman. the starting folder wouldn't matter would it? 

--

Thanks,

Fabian S.

OpenPGP: 3C3FA072ACCB7AC5DB0F723455502B0EEB9070FC

**Comment by maxking** [comment]
I meant the command `docker logs mailman-web` should print out some logs.

**Comment by fsantiago07044** [comment]
haha, sorry. thanks, yes it did:

SECRET_KEY is not defined. Aborting.

obviously i missed that definition. where do i find that value?

**Comment by maxking** [comment]
You set that as a environment variable. See `docker-compose.yaml` file and you will find out several environment variables defined for each container.

For mailman-web, please add a new `SECRET_KEY=<randomvalue>` and set it some long random value of your choice.

**Comment by fsantiago07044** [comment]
ok that did it and it's started. now, i'm trying to use apache on centos. i installed mod_proxy_uwsgi and I've defined my location with:

ProxyPass / uwsgi://172.19.199.3:8080/

but no good. apache logs complain there is no protocol handler available for this request. the mod_uwsgi proxy module is being loaded so I'm still confused. i know this isn't your purview but perhaps you've set this up before with apache so hence why i ask. thanks.

**Comment by fsantiago07044** [comment]
ok it works when i switch to http and port 8000. but the visible page now seems to be missing styles and/or assets.

**Comment by fsantiago07044** [comment]
my access logs show everything under /static/... is reporting 404.

**Comment by fsantiago07044** [comment]
/opt/mailman/web/static contains all of the files apache is complaining about. so, ??

**Comment by fsantiago07044** [comment]
nvm, rtfm....i got it.

**Comment by maxking** [comment]
Apache does have native support for uwsgi protocol using a plugin called `mod_uwsgi`. This plugin is usually included with the packaged version of Apache. I am not so sure about CentOS though.

https://github.com/maxking/docker-mailman#serving-static-files

Here are instructions about serving your static files. You basically just create an ALIAS rule for `/static` to the directory you just found (`/opt/mailman/web/static`)

**Comment by maxking** [comment]
Looks like your problem was solved, so I am closing this issue. Please re-open if that is not the case.

**Comment by fsantiago07044** [comment]
yes i had to structure my httpd conf in the correct order for it to function. thanks.
