### ISSUE TITLE
relay_domains postfix configuration problem when using existing virtual domains

### ISSUE THREAD

**Issue by fsantiago07044** [maxking/docker-mailman#164]
hello. in your doc you state to place into your postfix main.cf file the line:

relay_domains = regexp:/opt/mailman/core/var/data/postfix_domains

but if your server (as is mine) is already serving virtual domain / user email, this produces an error from postfix complaining of the domain being listed twice, if your added mm3 list domain matches a pre-existing virtual domain for which you're serving email, such as:

postfix/trivial-rewrite[19581]: warning: do not list domain xyz in BOTH virtual_mailbox_domains and relay_domains

commenting out the "postfix_domains" config line silences the error. 

not sure how to handle this though if you simply want to configure a domain which would only be used via mm3 and not for traditional email.

**Comment by maxking** [comment]
I am sorry but I don't know a lot of about Postfix, it might help to post it in mailman-users@python.org list .

**Comment by fsantiago07044** [comment]
On October 25, 2017 4:16:18 PM EDT, Abhilash Raj <notifications@github.com> wrote:
>I am sorry but I don't know a lot of about Postfix, it might help to
>post it in mailman-users@python.org list .

I looked at their online docs and they don't mention using that setting. So they're aware of it I'm assuming. 
--

Thanks,

Fabian S.

OpenPGP: 3C3FA072ACCB7AC5DB0F723455502B0EEB9070FC

**Comment by fsantiago07044** [comment]
see my answer in #165 . you can close this. thanks.
