### ISSUE TITLE
unknown recipient errors with lmtp / postfix connection

### ISSUE THREAD

**Issue by fsantiago07044** [maxking/docker-mailman#165]
i setup mm3 with your docker (thanks for this btw) and I use postfix. 

i can now create lists and subscribe users and they receive the subscription notice. 

but if I attempt to send an email to the list address, i receive back an undeliverable error msg email stating:

<"lmtp:[172.19.199.2]:8024"@<my domain>>: unknown user:
    "lmtp:[172.19.199.2]:8024"

looking at the email source, it seems as though the message is trying to be delivered to:

Final-Recipient: rfc822; "lmtp:[172.19.199.2]:8024"@<my email server's FQDN>
Original-Recipient: rfc822;test123@<my list's email domain>

does this seem correct to you?

**Comment by maxking** [comment]
Are you using the docker-compose.yaml file from this repository?

`172.19.199.2` is the IP assigned to the Core and MTA is supposed to deliver the emails to it Core and "lmtp:[172.19.199.2]:8024" is the Addresses where the MTA is supposed to deliver the email.

I am not exactly sure what is going on here, but it looks like a configuration error in Postfix.

**Comment by fsantiago07044** [comment]
probably, agreed; i did follow your online doc for setting all the postfix main.cf configs. i'm no postfix expert but i am familiar with it. 

it seems to be considering the lmtp address a recipient rather than routing the email over that way to the container / lmtp server. hmmmm, ?

**Comment by fsantiago07044** [comment]
and yes i am using the yaml file from here.

**Comment by fsantiago07044** [comment]
ok, mark sapiro over at the mm3 mailing list explained this to me and it works for me now as your doc lays out the setup instructions. 

basically, your mm3 list domain cannot be a virtual_mailbox_domain or a virtual_alias_domain in your email system (yet). a future version will fix this (of mm3). so you're good to go. and so am i. 

i created a new domain which did not exist on my email system and it works fine thru mm3 for a list. with your default setup instructions. thanks!

**Comment by maxking** [comment]
@fsantiago07044 thanks a lot for the explanation!
