### ISSUE TITLE
Typo in Dockerfile

### ISSUE THREAD

**Issue by dfukagaw28** [maxking/docker-mailman#177]
Should the following comment be fixed?

https://github.com/maxking/docker-mailman/blob/3434446987bc96686a3a70e05a6686fe67166114/web/Dockerfile#L36

```diff
- Expose port 8000 for uwsgi and port 8080 for http
+ Expose port 8000 for http and port 8080 for uwsgi
```

It's just a comment and does not change any behavior of machines, however, it still did change behavior of MINE...

Related commits:
* https://github.com/maxking/docker-mailman/commit/f6f4d36d64a61c5453ec8288f0f2b28bf93d665f
* https://github.com/maxking/docker-mailman/commit/a361b31923034afd2eacea92604ea673a358e7f2

**Comment by maxking** [comment]
Yes, it is left over from the previous commit that you correctly identified.

Pull requests welcome!

Thanks for opening an issue about it.
