### ISSUE TITLE
django_q tasks seems to be not running as expected

### ISSUE THREAD

**Issue by maxking** [maxking/docker-mailman#196]
It looks like django_q tasks aren't running as expected and hyperkitty doesn't have updated statistics unless restarted.

**Comment by zenhack** [comment]
Hi,

I'm in the midst of setting up a mailman3 server for the inkscape project. I'm not using the docker container, but I found this issue from a link in this thread:

https://lists.mailman3.org/archives/list/mailman-users@mailman3.org/thread/6P4GF6Q2M7Y7KUGNF6TI4EOACTVVM3MB/

..and we're having very similar symptoms. Has this been sorted out, or any progress been made? It seems likely that whatever misconfiguration happened for the docker container is also happening on our end.

**Comment by michaelachmann** [comment]
I just set up a mailman-server and am facing the same problem (see link in comment above). Has there been any progress, or can anyone point me in a direction where the bug comes from (from my understanding it only affects docker installations?)
