### ISSUE TITLE
Allow for logging to a central location instead of just files.

### ISSUE THREAD

**Issue by maxking** [maxking/docker-mailman#2]
For now logs are only files set to fixed file locations. Django (I think) supports logging to remote locations. It would be nice to allow for that in this setup.

**Comment by ishitatsuyuki** [comment]
I would propose like this: throw everything to Docker log by default, and let those professional configure fluentd for Django.

**Comment by maxking** [comment]
The userbase of Mailman isn't that familiar with how the Docker works. If I were to do it the "right" way, I would probably do as you mentioned, log to the Docker by default or maybe add a separate syslog container in compose file to do that.

But I think having the log files separately is a little helpful to get started with these images and for me to help with those having problems.

So, even though default isn't what I want, I am still considering how to give an option to people who want to install these images the "right" way.

**Comment by maxking** [comment]
Although, it seems that an option to log to stdout instead of the uwsgi log files seems like the best way to me.

**Comment by benbender** [comment]
I locally changed logging to stderr/stdout and I would appreciate to promote "the docker way" - but if you have another standpoint on this, it would be nice, to change the way the logs are created/configured. It would be much more flexible not to create the logfiles in uwsgi.ini/Dockerfile on buildtime, but configure them only via settings.py so they can be easily configured by providing your own settings_local.py

**Comment by maxking** [comment]
Doing it only via settings_local.py might be hard as that is Django configuration file and uwsgi.ini is for uwsgi.

You can actually configure Django's loggers(which logs to mailmanweb.log right now) to log to wherever you want using settings_local.py . I am totally up for moving to more *docker way* of logging to stdout/stderr (probably controlled by a configuration variable, but it being the default), I just haven't been able to get around to doing it.
