### ISSUE TITLE
Wrong uri for rolling releases in README.md

### ISSUE THREAD

**Issue by hrasmussendk** [maxking/docker-mailman#200]
The commands in the <a href="https://github.com/maxking/docker-mailman/blob/master/README.md#rolling-releases">Rolling releases section of the README file</a>, says `docker pull quay.io/mailman/mailman-web:rolling`, however this issues an `Error: Status 403 trying to pull repository`. The correct command must be `docker pull quay.io/maxking/mailman-web:rolling`.

**Comment by maxking** [comment]
Ah, thank you very much!

I will go ahead and update it!
