### ISSUE TITLE
Minor error in Docker commands to inspect the images for rolling releases in the README.md

### ISSUE THREAD

**Issue by hrasmussendk** [maxking/docker-mailman#202]
The <a href="https://github.com/maxking/docker-mailman/blob/master/README.md#rolling-releases">Rolling releases section of the README.md</a> file reads 

```
$ docker inspect mailman-web --format '{{json .Config.Labels }}' | python -m json.tool
```
It should read 
```
docker inspect --format '{{json .Config.Labels }}' mailman-core | python -m json.tool
```

**Comment by maxking** [comment]
Both of the commands work for me, did you had any errors with the command mentioned in the documentation?

**Comment by maxking** [comment]
(I updated the report to just enhance the readability of code a little, so that I see if there is something  that I was missing)

**Comment by hrasmussendk** [comment]
Yes, I get
```
# docker inspect mailman-core --format '{{json .Config.Labels }}' | python -m json.tool
Error: No such image, container or task: --format
```

**Comment by maxking** [comment]
Hmm, weird. It works for me.

I will update it anyway, I think it is the correct one.
