### ISSUE TITLE
Invalid confirm email address while unsubscribing

### ISSUE THREAD

**Issue by alekh16** [maxking/docker-mailman#206]
When I send an email to listname-leave@domain.com, I get an confirmation email to reply to. But the email address has the rfc2369 appended to it by default. It looks something like listname-confrim+rfcCode@domain.com instead of listname-confirm@domain.com

<img width="993" alt="screen shot 2017-12-14 at 2 25 23 pm" src="https://user-images.githubusercontent.com/10241093/34010424-ab70169c-e0da-11e7-9620-a7c28cacc3e5.png">

cc: @maxking

**Comment by maxking** [comment]
Yes, that is expected. You can reply to the email, without changing anything to get unsubscribed.

**Comment by alekh16** [comment]
Thanks for the prompt reply, really appreciate it @maxking 

I tried to reply without changing anything to get unsubscribed but I got a mail saying


Your document: | Re: confirm c42800a9ba1693ca66481925738295c74a92607e
-- | --
was not delivered to: | listname-confirm+c42800a9ba1693ca66481925738295c74a92607e@domain.com
because: | unknown user: "listname-confirm"

However, If i keep everything intact and send the reply to listname-confirm@domain.com , I get successfully unsubscribed. So am wondering if the email should have been listname-confirm@domain.com and not listname-confirm+code@domain.com?

Help is appreciated. Thanks

**Comment by maxking** [comment]
Are you using the container images from this repository?

If yes, which version of the images are you using. I do remember a regexp bug which could cause this with postfix, assuming that you are using that with Mailman.

The bug causes postfix to treat listname-confirm+code@domain as a new address and thus doesn't deliver it Mailman, when in fact it shouldn't do that, or atleast didn't do previously.

**Comment by alekh16** [comment]
Yes, using container images from this repository. The image version is 0.1 for both core and web.
`maxking/mailman-web:0.1 maxking/mailman-core:0.1`

And yes, using postfix with mailman. 
I understand the bug but is there a way that I can fix it?

**Comment by maxking** [comment]
This bug should now be fixed, it hasn't been released yet I think.

I am going to close this issue for now as it is an upstream bug.
