### ISSUE TITLE
Update to Alpine 3.7

### ISSUE THREAD

**Issue by maxking** [maxking/docker-mailman#207]
Update the images to Alpine 3.7 verison

**Comment by warsaw** [comment]
Is this to reduce the size of the images?  Should we do the same thing [over here](https://gitlab.com/python-devs/ci-images)?

**Comment by maxking** [comment]
Yes, I use Alpine in these images mostly because alpine is much more tiny than other distro base images.

Apline however doesn't have libc and and is based of musl-libc and busybox(instead of core-utils). In prod environment I don't think we care much about these utilities, but in development it might affect installation of some c based extensions. In Mailman we don't have anything with c extensions I guess so it has been working quite well.

Having said that, musl-libc is still supposed to be a drop-in replacement for libc and _should_ support most of the things. I am not sure about what might break. 

One idea for python-devs/ci-images would be to have two versions of images one built on alpine and other one that currently exists. This would give people options to choose from. Many other container images do this.

**Comment by warsaw** [comment]
Ah, that's interesting.   I see a [few open issues](https://bugs.python.org/issue?%40columns=id%2Cactivity%2Ctitle%2Ccreator%2Cassignee%2Cstatus%2Ctype&%40sort=-activity&%40filter=status&%40action=searchid&ignore=file%3Acontent&%40search_text=alpine&submit=search&status=-1%2C1%2C2%2C3) in upstream Python with Alpine, so it seems to be used a bit, though I don't know how widely.

Anyway, for ci-images, just something to think about if the image size gets to be too burdensome.

**Comment by maxking** [comment]
I will open an issue there to track and explore creating an Alpine version of the images.

**Comment by maxking** [comment]
We are already at Alpine 3.12. Closing this.
