### ISSUE TITLE
web container build fails

### ISSUE THREAD

**Issue by pgollor** [maxking/docker-mailman#208]
The build for version 0.1.3, 0.1.4 and 0.1.5 fails with the following error:
```
Collecting Django>=1.8 (from django-mailman3==1.1.0)
  Downloading Django-2.0.tar.gz (8.0MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-DED89T/Django/setup.py", line 32, in <module>
        version = __import__('django').get_version()
      File "django/__init__.py", line 1, in <module>
        from django.utils.version import get_version
      File "django/utils/version.py", line 61, in <module>
        @functools.lru_cache()
    AttributeError: 'module' object has no attribute 'lru_cache'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-DED89T/Django/
```

I try to find out why it fails for django. The problem comes with python2. The change from `python:2.7-alpine3.6` to `python:3.6.4-alpine3.6` solve the problem. Is there any reason to use python 2 instead of python 3?

**Comment by maxking** [comment]
Yeah, this can probably be fixed by moving the `pip install django<1.12` before the `pip install django-mailman3` in the Dockerfile.

Yes, the current django apps are based of Python2 only.

**Comment by pgollor** [comment]
https://docs.djangoproject.com/en/1.11/topics/python3/

**Comment by maxking** [comment]
Yes, Django 2.0 doesn't support Python 2. Ideally, pip should take care of that part and install only compatible versions, but I am not sure the reason why it doesn't in case of Django.

If you want to install django in Python 2, choose versions `<=1.11`

**Comment by pgollor** [comment]
Yes, i tried it but postorius or django-mailman tries to install django 2.0 automatically. But v0.1.7 works fine. Thanks.
