### ISSUE TITLE
integrate MTA

### ISSUE THREAD

**Issue by PowerPan** [maxking/docker-mailman#210]
Hey

it would be very nice if you could add a MTA in the Dockercompose File ;)

**Comment by maxking** [comment]
Yeah, I have been thinking about doing so. However, I have been thinking about whether to create my own image for Postfx (or whichever MTA i will end up choosing finally) or grab one already existing one.

So, adding an MTA and Web Server is kinda on my agenda, no ETAs yet though.

**Comment by aiomaster** [comment]
Hi,
I use https://github.com/hardware/mailserver together with these mailman images. It is working very well and has everything I need.
I don't see the value in maintaining just another postfix image, if there are good enough ones out there.
The mailman images should be on focus.

**Comment by anthony-halim** [comment]
> Hi,
> I use https://github.com/hardware/mailserver together with these mailman images. It is working very well and has everything I need.
> I don't see the value in maintaining just another postfix image, if there are good enough ones out there.
> The mailman images should be on focus.

Hi, could you explain more how to setup the postfix? I am currently having problems on where to start. I am new to this email businesses. Thank you!
