### ISSUE TITLE
Confirmation emails have an URL with the private address of the container

### ISSUE THREAD

**Issue by carlosm3011** [maxking/docker-mailman#211]
Instead of a link to http://my.mailmansite.com the link points to https://172.19.199.3:8000 ....

**Comment by maxking** [comment]
It usually is because of Nginx rewriting the URLs when forwarding the requests to uwsgi. I have seen this before but can't remember the answer of the top of my head.

Maybe try this:
```
		  proxy_set_header Host $host;
```
This setting is for Nginx, you can  use the equivalent setting if you are using another web server.

**Comment by carlosm3011** [comment]
I’ll git it a try. However, the wrong url appears in the body of an 
email. I think it’s being generated by some django component, but for 
the life of me I can’t find which setting to tune.

I’ve already set SERVE_FROM_DOMAIN and confirmed it’s being accepted 
by the container.

I *think* it has to be a django.allauth setting, but I’m not sure.

thanks

Carlos

**Comment by maxking** [comment]
It is indeed created by django allauth, however, the HOST part of the url isn't something static and is probably dependent on the request coming in. Ideally, the same django site can be served via multiple domain names(Hosts). 

I am sure you can find an open issue somewhere in this project that answers this.

**Comment by carlosm3011** [comment]
Well, the nginx setting seems to have done the trick!! Thank you!

**Comment by maxking** [comment]
Awesome!
