### ISSUE TITLE
README.md Associating rolling releases with Mailman issues

### ISSUE THREAD

**Issue by hrasmussendk** [maxking/docker-mailman#212]
In [a post on lists.mailman3.org](https://lists.mailman3.org/archives/list/mailman-users@mailman3.org/message/UCDUMY3JDEN2GMPYQNBSKTBFHWXDR5RZ/) I tried to reach out for help associating rolling releases with [Mailman issues](https://gitlab.com/mailman/mailman/issues), and @maxking answered that 

>Running releases are built weekly (and with every commit to docker-mailman
>repo), and use the git heads from gitlab for *all* the components.
>
>To be more specific, you can get the commit version for each component and check
>that in the git tree to find out if any particular issue is fixed before that.
>
>You can use `docker inspect` as mentioned in the docs to get the commit version.

The `docker inspect` command only shows the latest installed commit (I suppose). I want to be able to associate each "number" (I don't know if it's commit numbers) in the list when doing a docker pull quay.io/maxking/mailman-core:rolling, 

>81033e7c1d6a: Already exists
>9b61101706a6: Already exists
>35b21c1a8b97: Already exists

to a fix in the core or web on GitLab. I still haven't found the connection. I suppose it isn't just like that, but what should I do.

Could the README explain that in more details?

**Comment by maxking** [comment]
This is tricky and I am not sure how to achieve this.

Every-time rolling releases are built (the build system is broken for now), we pull the latest commit available on the git-master, which passed all the tests.

The (first) problem with associating each "number"  that you do docker pull for is that there is no sequential number for every build of rolling releases. Every time one is built, the same 'rolling' tag is applied to it. 

      81033e7c1d6a: Already exists
      9b61101706a6: Already exists
      35b21c1a8b97: Already exists

^ These are image layers from a single image, but can be same across different images, depending on what changed in the new image.

Except date (which again, will be good once the build system is back running properly), there is no clear way I can see to associated which rolling release has fixes for which issues.

**Comment by maxking** [comment]
Because you use it, I just wanted to let you know that Rolling releases are now built everyday.

**Comment by maxking** [comment]
I am not sure what needs to be done for this issue, please feel free to re-open this issue.

http://mailman.readthedocs.io/en/latest/src/mailman/docs/NEWS.html This page usually has all the changes in the master branch and more-or-less should be in the rolling releases. Sometimes the builds breaks and it takes me a few days before I can investigate why (which is when it gets out of sync with the list of changes)
