### ISSUE TITLE
Default endpoint

### ISSUE THREAD

**Issue by legraina** [maxking/docker-mailman#215]
Hi,

I'm not able to mount mailman on specific endpoint. For example, I would like to have http://mysite.com/mailman/.... The problem with that is that all the links within mailman do not take into account the endpoint (i.e., /mailman/).
Is there any option to obtain such a result please ?

Thanks

**Comment by maxking** [comment]
It is hard to get that with the current setup.

You would have to modify the `urls.py` under in mailman-web container to add a prefix, but currently there is no way to do this with a configuration parameter or something. 

I wouldn't mint adding such a feature in future though, it would be as simple as setting an environment variable in Docker container and reading that in URLs to setup the prefix.

**Comment by legraina** [comment]
I've seen the urls.py file, but I think it's not enough as you also need to change the link within the pages ...
The environment variable will be really nice indeed.

**Comment by maxking** [comment]
Which links within the pages?

**Comment by legraina** [comment]
When you will be clicking on Postorious, you do not want to get redirected to /postorius/lists but to /mailmann/postorius/lists

**Comment by maxking** [comment]
Those are relative URLs, so they would change automatically.

I have done this before, using a URL prefix in Nginx configuration. 

```
location /mailman {
    uwsgi_pass 172.19.199.3:8080;
    uwsgi_param SCRIPT_NAME /subpath; # explicitly set SCRIPT_NAME to match subpath
    uwsgi_modifier1 30; # strips SCRIPT_NAME from PATH_INFO (the url passed to Django)
    include uwsgi_params;
}
``` 
I *think* there is some issue in the closed issues, which might be related. I can find it out later for you if this doesn't work.

**Comment by legraina** [comment]
I'm trying to use this config:

     location /mailman/ {
        uwsgi_param SCRIPT_NAME /mailman/; # explicitly set SCRIPT_NAME to match subpath
        uwsgi_modifier1 30; # strips SCRIPT_NAME from PATH_INFO (the url passed to Django)
        uwsgi_param UWSGI_SCHEME http; # to change the connection scheme from https to http
        include uwsgi_params;
        uwsgi_pass mailman;
    }

When I try localhost/mailman, I'm being redirected to /postorius/lists/ instead of /mailman/postorius/lists/. I think that the uwsgi_params are not passed correctly.

**Comment by maxking** [comment]
Can you try this (essentially same, but rearranged order):

```
location /mailman3/ { 
# First attempt to serve request as file, then 

    uwsgi_pass 172.19.199.3:8080; 
    include uwsgi_params; 
    uwsgi_read_timeout 300; 
    uwsgi_param SCRIPT_NAME /mailman3; 
    uwsgi_modifier1 30; 
} 
```

It should work according to https://lists.mailman3.org/archives/list/mailman-users@mailman3.org/message/QBKKJ7EUHUF5DBLTCY2O6A65ERLOYKU3/ , which I tested some time ago.

**Comment by legraina** [comment]
Using the port 8080 worked for me.
Thanks a lot !

**Comment by simonwiles** [comment]
Would there still be any appetite for a mechanism to configure `urls.py` (probably best from environment variables, or perhaps with a config override)?  I'd like to customize some of the URLs, but at the moment I can only do that by mounting files directly into `/opt/mailman-web`, which is obviously not ideal.  Would a PR be welcome?
