### ISSUE TITLE
MAILMAN_REST_PASSWORD not injected when container instantiated

### ISSUE THREAD

**Issue by skoranda** [maxking/docker-mailman#219]
The README.md documentation for web includes this:

MAILMAN_REST_PASSWORD: Mailman's REST API user's password. Default value is restpass

First, I am surprised that this is detailed on the web documentation since I understand that the REST user and password need to be set in core in the [webservice] section of the configuration.

Second, looking at the entrypoint script I do not see that the environment variable MAILMAN_REST_PASSWORD is ever consumed and injected, for either web or core.

Can you confirm that the environment variable is not being consumed and that it should be consumed by the entrypoint script for core?

If so it is a straightforward patch and I am happy to submit a pull request.

Thanks for consideration.

**Comment by skoranda** [comment]
Oh, I see. The idea was that expert users can just inject the entire mailman.cfg or extra mailman-extra.cfg, and of course Mailman-web is consuming the information because Django is of course a REST client.

I did just submit a PR with changes so that the REST port, user, and password can be injected with environment variables.

Thanks.

**Comment by maxking** [comment]
It is not easy to configure Core completely using environment variables, so I had to provide a way to configure it properly. The current way isn't working out so well, and soon we will have to do something about it.

Django is also on the similar place and also has a settings-local.py support to configure it.
