### ISSUE TITLE
When SERVE_FROM_DOMAIN is specified, mailman-web fails with with no table `django_site`

### ISSUE THREAD

**Issue by maxking** [maxking/docker-mailman#228]

**Comment by NilsGriebner** [comment]
Facing the same issue. Is there a way to fix this?

**Comment by ehuelsmann** [comment]
> These are the settings that you MUST change in your docker-compose.yaml before deploying

SERVE_FROM_DOMAIN should be listed in the docker-compose.yaml for clarity. With some fiddling, I've found out, but it's not immediately apparent where to add this setting...
