### ISSUE TITLE
setting mailman.cfg via /opt/mailman/core/mailman-extra.cfg failed

### ISSUE THREAD

**Issue by y0va** [maxking/docker-mailman#230]
For exchanging the standard mta config from exim to postfix, the proposed way in the [readme](https://github.com/maxking/docker-mailman#setting-up-your-mta) doesn't work for me. If I create a file `/opt/mailman/core/mailman-extra.cfg`  with the postfix configuration, it doesn't show up in the mailman conf after restarting the container.

Using `/opt/mailman/mailman.cfg`as proposed [here](https://github.com/maxking/docker-mailman/tree/master/core#running-mailman-core), didn't work neither.
The only way I was successful in including the postfix config is to link a file as volume into the docker, and set `MAILMAN_CONFIG_FILE` accordingly.

**Comment by maxking** [comment]
https://github.com/maxking/docker-mailman/blob/master/core/docker-entrypoint.sh#L152
It should be added to the configuration that is used by Mailman, it is appended to the config generated at runtime.

**Comment by maxking** [comment]
The 2nd part is wrong, thanks for pointing it out. I will update it's documentation. `/opt/mailman/mailman-extra.cfg` is the only one that should be added to config.

**Comment by y0va** [comment]
Ah OK. Then the readme is wrong. it should be `/opt/mailman/mailman-extra.cfg` and not `/opt/mailman/core/mailman-extra.cfg`

**Comment by maxking** [comment]
Docs is correct in one place, the one in core/Readme.md isn't.

**Comment by maxking** [comment]
I'd need more details about why it doesn't work if you place configs at /opt/mailman/core/mailman-extra.cfg.

Can you please share the output of `docker logs mailman-core` after you started/re-started the container?

**Comment by y0va** [comment]
Thank you for your help, it works for me now. I was a bit puzzled by your usage of host directories in the docs. For me it would be more easy if you would use relative paths from the docker-compose directory or the directory structure from within the docker containers, which we see from the logs.

For me it looks eg:
```
root@strix /data/domains/mailman.ecobytes.net # docker-compose logs mailman-core | grep mailman-extra.cfg
mailman-core    | Found configuration file at /opt/mailman/mailman-extra.cfg
```

**Comment by maxking** [comment]
I guess that makes sense, I will update the docs to reflect the same.

**Comment by duck-rh** [comment]
I made some screenshots to show you.

![20230619-203508_screenshot](https://github.com/maxking/docker-mailman/assets/19259504/def85452-80db-4a08-b2bb-172ca095b809)
![20230619-203514_screenshot](https://github.com/maxking/docker-mailman/assets/19259504/e987156d-b142-4e03-ac68-c8a6b8914210)
