### ISSUE TITLE
github, gitlab google not working as social logins 

### ISSUE THREAD

**Issue by y0va** [maxking/docker-mailman#231]
mailmanweb.log shows:
https://gist.github.com/y0va/c1447fc5bd671531ec7f869ac2e91c60

This may also be Django upstream. 

Workaround by disabling those three in settings_local.py:

```
INSTALLED_APPS = (
    'hyperkitty',
    'postorius',
    'django_mailman3',
    # Uncomment the next line to enable the admin:
    'django.contrib.admin',
    # Uncomment the next line to enable admin documentation:
    # 'django.contrib.admindocs',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_gravatar',
    'paintstore',
    'compressor',
    'haystack',
    'django_extensions',
    'django_q',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'django_mailman3.lib.auth.fedora',
    'allauth.socialaccount.providers.openid',
 #   'allauth.socialaccount.providers.github',
 #   'allauth.socialaccount.providers.gitlab',
 #   'allauth.socialaccount.providers.google',
)
```
which has to be placed in  `/opt/mailman/web` as stated in https://github.com/maxking/docker-mailman#configuration

**Comment by y0va** [comment]
The strange place for settings_local.py comes from:
 https://github.com/maxking/docker-mailman/blob/186bdcef8acde4abbb66fa8d88b78e28c9d09d5a/web/docker-entrypoint.sh#L105

**Comment by maxking** [comment]
Docs are correct, `/opt/mailman/web/` from the host is mounted inside the container at `/opt/mailman-web-data/` and so the paths that you see from outside is going to be `/opt/mailman/web/settings_local.py`.

**Comment by maxking** [comment]
Also, social logins don't work by default. You'd have to configure them to work. 

See this instruction as an example of howto setup google for login: http://django-allauth.readthedocs.io/en/latest/providers.html#django-configuration

You can find other providers in django-allauth docs too. I should probably add this explicitly in docs somewhere.

**Comment by y0va** [comment]
Yeah, I was a bit puzzled because the icons were there at the login screen but were not functional. Therefore I would disable those three social auth plugins  by default too.

**Comment by maxking** [comment]
This should be handled upstream, I have a bug open there to not show Social Logins that are enabled but not configured.

https://gitlab.com/mailman/django-mailman3/issues/5
