### ISSUE TITLE
Update Django in dev builds

### ISSUE THREAD

**Issue by aiomaster** [maxking/docker-mailman#242]
Hi @maxking,

I think the django-version in the dev builds is too old.
This propably causes this error:
https://gitlab.com/mailman/django-mailman3/issues/15

Can we just increment the version to 1.11 here:
https://github.com/maxking/docker-mailman/blob/bbb3030359692003de81ea95dd8a11be29f75cf1/web/Dockerfile.dev#L32
and build a new dev container?
Otherwise it is just broken.

Thanks!

**Comment by maxking** [comment]
Thanks for reporting the issue, I will go ahead and fix it.
