### ISSUE TITLE
rolling build not working anymore?

### ISSUE THREAD

**Issue by aiomaster** [maxking/docker-mailman#248]
Hi @maxking,
the last rolling release is more than a week old:
https://quay.io/repository/maxking/mailman-web?tab=tags

Could it be, that the build fails or is it on hold for other reasons?
Thanks

**Comment by maxking** [comment]
It has been failing for various reasons in past week :)

I haven't had time to investigate why, but if you want to, please feel free. The CI jobs run on Circle CI and they have public logs available.

**Comment by maxking** [comment]
It happens sometimes when the master branch is broken for any of the projects in the release.

**Comment by maxking** [comment]
This should now be fixed, but the workflow will run tomorrow ;-)

**Comment by maxking** [comment]
Actually, workflow ran too!
