### ISSUE TITLE
Web Serving url in Documentation

### ISSUE THREAD

**Issue by pc-magas** [maxking/docker-mailman#259]
I try to create a local setup to my computer in order to test it/ have a look on how it works. Therefore  want to know which urls are accesible via the web. For example what I will type to my browser in order to make hyperkitty accessible to a local setup to my browser?

I have looked and drilled the whole documentation to figure it out.

**Comment by maxking** [comment]
If you are using the docker-compose.yaml file from this repo, the web server should be listening at `http://172.19.199.3:8000`

**Comment by roddajohn** [comment]
Related issue: if I am trying to test the API / write a simple Django app to play with the API, what should the url be?  I tried `localhost:8001` and `localhost:8001` as well as `172.19.199.3:8001` and `172.19.199.3:9001` all through cURL on the machine where the Dockers are running.  All of those curls (when I give it the default `restadmin` and `restpass` give me connection refused.

For example:
<img width="948" alt="screen shot 2018-07-15 at 6 52 15 pm" src="https://user-images.githubusercontent.com/10851328/42739187-39f2d9ae-8860-11e8-8c29-2e332020cd42.png">

Thanks for any assistance you can provide.

**Comment by maxking** [comment]
Core is in a different container, whoose IP is by default set to `172.199.19.2`

**Comment by roddajohn** [comment]
Thanks!
