### ISSUE TITLE
Location of Log Files for REST API

### ISSUE THREAD

**Issue by roddajohn** [maxking/docker-mailman#260]
Hi,

A POST call to `<API URL>/3.1/lists` with with parameter `fdqn_hostname` in the POST data is throwing `A server error has occurred.  Please contact the administrator.` Where can I find the logs for the REST API so that I can investigate what this error is?

Thanks!

**Comment by maxking** [comment]
Logs are available in `/opt/mailman/core/var/logs/mailman.log`
