### ISSUE TITLE
Please Release With Postorius 1.2.2

### ISSUE THREAD

**Issue by jGleitz** [maxking/docker-mailman#268]
Please publish a stable docker version of `mailman-web` that contains Postorius 1.2.2, as it fixes this issue: https://gitlab.com/mailman/postorius/issues/145

**Comment by maxking** [comment]
Done, should be updated now.

**Comment by jGleitz** [comment]
Wow, that was fast. Thank you!

**Comment by maxking** [comment]
You're welcome :)
