### ISSUE TITLE
0.1 versions are no longer stable or maintained ?

### ISSUE THREAD

**Issue by Dragnell87** [maxking/docker-mailman#273]
There is any special procedure to use 0.2 version?

**Comment by maxking** [comment]
There hasn't been any upstream releases, so no, 0.1 is no longer updated.

**Comment by maxking** [comment]
0.2 should be simple to upgrade for the Images themselves, but please see the changelog for the upstream packages.

**Comment by Dragnell87** [comment]
Ok thanks, i will look the change log in upstream.
