### ISSUE TITLE
Improve the Exim setup instructions

### ISSUE THREAD

**Issue by maxking** [maxking/docker-mailman#281]
More details are there in this thread[1] on mailman-users@mailman3.org. The current instructions are mostly specific to Debian, I am not sure if they would change with distro, but there seems to be some differences when using CentOS7.

One specific suggestion:
```
 For example: 

"To use Exim4, it should be setup to relay emails from 172.19.199.3 and 172.19.199.2." 

I would change the above line to include the actual setting to change in the exim.conf file: hostlist 

relay_from_hosts = localhost : 172.19.199.3 : 172.19.199.2 : 172.19.199.1
```

https://lists.mailman3.org/archives/list/mailman-users@mailman3.org/thread/W4N3V53DHKLJT7XKOADSBL6VHDZRYXOF/

**Comment by brianemwd** [comment]
I am not sure how this would work for Debian but I found it easy to use the /etc/localdomains file for Exim on CentOS 7:

domainlist local_domains = lsearch;/etc/localdomains

To include a domain, just add it on its own line to /etc/localdomains. I don't think you even have to restart Exim for it to pick it up.
