### ISSUE TITLE
New mailman-web release with ability to manager non-members

### ISSUE THREAD

**Issue by dansou901** [maxking/docker-mailman#289]
Hi @maxking,

can we have a new mailman-web release with merge request https://gitlab.com/mailman/postorius/merge_requests/367 built in? This would help a lot. Thank you!

Regards,
dansou901

**Comment by maxking** [comment]
Mailman-web release won't help, since the upstream hasn't released a new version of Postorius with that MR yet. :)

**Comment by dansou901** [comment]
Ok, so can you discuss with the other mailman developers to do a new release of postorius then?

**Comment by maxking** [comment]
Today might be hard, but I'll try to cut out a release tomorrow.

**Comment by dansou901** [comment]
That's absolutely fine, take your time!

**Comment by dansou901** [comment]
Thank you very much! I'll try once you upload a new build of mailman-web to docker hub.

**Comment by dansou901** [comment]
Just saw there's a new build already, but I just don't want to switch to rolling...

**Comment by maxking** [comment]
yeah, rolling builds are automatically built on every commit. I probably should automate the tag and publish workflow too.

thanks,
Abhilash Raj (maxking)

**Comment by dansou901** [comment]
Just for your attention, this also affects https://lists.mailman3.org/archives/list/mailman-users@mailman3.org/thread/C7CLPT5KBHPU663EVKESIXUPGOT5BOGA/ (the original mailman list post asking for this)

**Comment by maxking** [comment]
tagged and pushed mailman-web and core on docker hub.

quay has mailman-web, but push for core seems to be failing for some reason.

Look for 0.2 tag or 0.2.1
