### ISSUE TITLE
Document how to update installations

### ISSUE THREAD

**Issue by maxking** [maxking/docker-mailman#293]
The documentation steps are simple:

```bash
$ docker-compose stop
$ docker-compose rm
$ docker pull maxking/mailman-core:$tag
$ docker pull maxking/mailman-web:$tag
$ docker-compose up -d
```

Make sure that you use the appropriate `-f docker-compose.yaml` file in all the above commands.

**Comment by brianemwd** [comment]
Do I need to replace the $tag with:

 

0.2 or 0.2.1

 



 

Brian Carpenter
Owner



Providing Cloud Services and more for over 15 years.


T: 336.755.0685
E: brian@emwd.com
www.emwd.com



 

 <https://www.facebook.com/pages/EMWDcom/192156034142506>  <http://www.linkedin.com/in/brianemwd>

**Comment by maxking** [comment]
You can use either, both of them point to same image. 0.2 is a moving target and the next time I publish a 0.2.x image, 0.2 will point to that (always the latest version of 0.2.x).

**Comment by maxking** [comment]
On January 25, 2019 8:27:33 PM PST, brianemwd <notifications@github.com> wrote:
>You might want to add to the bottom of the update instructions:
>$ docker-compose start mailman-core
>$ docker-compose start mailman-web

Docker-compose up -d 

That should take care of starting all services.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by maxking** [comment]
How long did you wait for? It usually takes anywhere between 10 to 30 seconds to bring up the REST Runners.

You can check if the container itself came up by running `docker ps`. According to the docs, `docker-compose up` should take care of bringing up the containers. (`-d` flag makes it run in background)

**Comment by brianemwd** [comment]
That is a good point. I did not wait very long at all. I will do that next time there is an update/upgrade. Great help, thanks!
