### ISSUE TITLE
REST API not avaiable

### ISSUE THREAD

**Issue by deron2** [maxking/docker-mailman#296]
I am setting up Mailman3 using your Docker.

When using the Web-Interface, there is an error when signing up or logging in.
The logs show this:
https://pastebin.com/xeSJrGA3
Somehow it can not connect to the REST API. However,
`curl --user restadmin:restpass 172.19.199.2:8001/3.0/system/versions` still returns the expected result: 
`{"mailman_version": "GNU Mailman 3.2.0 (La Villa Strangiato)", "python_version": "3.6.4 (default, Jan 10 2018, 05:26:33) \n[GCC 5.3.0]", "api_version": "3.0", "self_link": "http://172.19.199.2:8001/3.0/system/versions", "http_etag": "\"acafff7f78f35f8341133d620e6887c819e97c24\""}`

My docker-compose.yaml is fairly stock:
https://pastebin.com/ZBaMrU5v

**Comment by deron2** [comment]
This error happens when Postfix can not send mails via SMTP

**Comment by maxking** [comment]
Yes, that's right. Do you have Postfix setup correctly along with the settings in mailman web's `settings_local.py`? I suspect that bad SMTP settings for mailman-web is the reason for this.
