### ISSUE TITLE
Mailman User and Group

### ISSUE THREAD

**Issue by brianemwd** [maxking/docker-mailman#297]
When installing Mailman from your docker image, my understanding was that a mailman user and group was to be created. Is that true? Because that is not the case with my installation. Did I miss something in the documentation?

Any assistance would be appreciated. Thanks!
Brian

**Comment by maxking** [comment]
No, you don't have to create any users or groups when using container images.

**Comment by brianemwd** [comment]
Thank you. I was somewhat concerned about that.
