### ISSUE TITLE
Hyperkitty not updating

### ISSUE THREAD

**Issue by brianemwd** [maxking/docker-mailman#298]
The main HK page for each list is not updating with the latest posts. The posts are showing up when viewing a particular month but not on the main HK page. Only restarting the Docker container does the posts show:

docker-compose restart mailman-web

There is one exception, the first post to a newly created list shows up automatically. Just not any subsequent ones.

This behavior started after the recent upgrade to Postorius and Core.

**Comment by brianemwd** [comment]
Does this perhaps have something to do with Django-Q tasks failing?

null value in column "description" violates not-null constraint
DETAIL: Failing row contains (6, *****.mailman3.*******.***, Mylist, null, [Mylist] , 2, 2019-02-06 05:14:41.821683+00, *****.mailman3.*******.***).
: Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
return self.cursor.execute(sql, params)
psycopg2.IntegrityError: null value in column "description" violates not-null constraint
DETAIL: Failing row contains (6, *****.mailman3.*******.***, Mylist, null, [Mylist] , 2, 2019-02-06 05:14:41.821683+00, *****.mailman3.*******.***).

The above error is happening for all of my lists. It seems to impact Hyperkitty and it started happening with the last update that Maxking put out:

https://lists.mailman3.org/archives/list/mailman-users@mailman3.org/thread/DB63HY3A5I5IAQ3R4MD3BWUJH3KYNTMX/

**Comment by maxking** [comment]
The last change didn't really change anything in HK, so this is interesting. I will work on investigating what is the core issue behind this.

**Comment by brianemwd** [comment]
I am wondering if this has more to do with Django then HK. According to my logs, it definitely started right after I upgraded.

**Comment by brianemwd** [comment]
What is the status on this bug?

**Comment by clemenbor** [comment]
In my case not even doing a "docker-compose restart mailman-web" will make a proper refresh. Any ideas here what is the cause? I can't see anything within the logs....
