### ISSUE TITLE
Environment variable: HYPERKITT[Y]_API_KEY

### ISSUE THREAD

**Issue by worikgh** [maxking/docker-mailman#299]

**Comment by worikgh** [comment]
In the documentation the environmnet variable HYPERKITT_API_KEY is HYPERKITTY_API_KEY some times.

At https://github.com/maxking/docker-mailman/blob/master/core/README.md#configuration it is HYPERKITT_.. and at https://github.com/maxking/docker-mailman/blob/master/core/README.md#running-mailman-core and in supplied docker-compose.yaml it is HYPERKITTY_..

**Comment by worikgh** [comment]
It is unclear from the README.md where environment variables should be set.  There are a number set in the various (3) .yaml files though only one is mentioned in the documentation.
In https://github.com/maxking/docker-mailman#mailman-core it says the variables must be set, but not where.
At https://github.com/maxking/docker-mailman#mailman-web it says `These are the settings that you MUST change before deploying` and as far as I can tell four of the variables are not set any where.
Some are gotten from the environment in settings.py so I guess I must set them in the environment.
I am coming to this with close to zero knowledge about django and/or python

**Comment by maxking** [comment]
Anywhere there is a `Y` missing in `HYPERKITTY` it is an error and should be fixed.

Vars must be set in `docker-compose.yaml` file or whichever one you are using (-mysql.yaml or -postorius.yaml) under the right section (core, web)

**Comment by worikgh** [comment]
Helpful, thank you.

Is the `docker-compose.yaml`, and `docker-compose-postorius.yaml` the only place to set environment variables? (That seems to be what you are saying, I want to be clear)
Can I disregard `...-mysql.yaml` as I am using the default, postgresql?
I found I had to set my `ALLOWED_HOSTS`  in `settings_local.py`.  Should I be setting that, too, in a yaml file?

cheers

**Comment by maxking** [comment]
You have to set it in only one yaml file.

When you run `docker-compose` commands, it looks for a config file, by default, it looks for `docker-compose.yaml`. If you want to use `mysql` instead of `postgres`, you need to tell `docker-compose` to use that config file with `docker-compose -f docker-compose-mysql.yaml`.

So, if you want to  use only postgres as database, forget about all the yaml files except `docker-compose.yaml` and only make changes in there. 

And no, you don't have to make `ALLOWED_HOSTS` changes in `settings_local.py`.

**Comment by worikgh** [comment]
Given the domain MYDOMAIN.COM if I take it out of ALLOWED_HOSTS in settings_local.py, and  I put the line:
`- ALLOWED_HOSTS=MYDOMAIN.COM` 
into `docker-compose.yaml` or `docker-compose-postorius.yaml` environment section for `mailman-web` I get a `Bad Request (400)` error and /opt/mailman/cor/var/logs/mailmanweb.log` it helpfully says:
`Invalid HTTP_HOST header: 'MYDOMAIN.COM'. You may need to add 'MYDOMAIN.COM' to ALLOWED_HOSTS.`

So I do not understand what I am supposed to do.  What did I do wrong?

**Comment by maxking** [comment]
Instead of `ALLOWED_HOSTS` use `SERVE_FROM_DOMAIN`.

So set
`-SERVE_FROM_DOMAIN=MYDOMAIN.COM` in your `docker-compose.yaml` under `mailman-web` section.

**Comment by worikgh** [comment]
Thank you.
Can I ignore the other `.ymal` files?

**Comment by maxking** [comment]
Yes.

**Comment by maxking** [comment]
I am closing this issue, please re-open if you have more questions.

The typo has been fixed and it is consistently called `HYPERKITTY_API_KEY` now.
