### ISSUE TITLE
Add Moderator displays unsubstituted variables

### ISSUE THREAD

**Issue by worikgh** [maxking/docker-mailman#302]
When adding a moderator to a list I saw the following string in my browser:

```
<div class="alert alert-success">%(email)s has been added with the role %(role)s</div>
```

This appears after I hit `Add Moderator`

**Comment by maxking** [comment]
This is a bug and should be reported to upstream.

**Comment by maxking** [comment]
https://gitlab.com/mailman/postorius/issues/327

Reported upstream.
