### ISSUE TITLE
Missing from documentation for postfix

### ISSUE THREAD

**Issue by worikgh** [maxking/docker-mailman#304]
Must  add 172.19.199.3 and 172.19.199.2 to
  mynetworks in /etc/postfix/main.cf

**Comment by maxking** [comment]
https://github.com/maxking/docker-mailman#setting-up-your-mta

It is already there.

**Comment by worikgh** [comment]
I disagree that it is there
```
To use Postfix, it should be set up to relay emails from 172.19.199.2 and 172.19.199.3. The mailman specific configuration is mentioned below which you should add to your main.cf configuration file, which is typically at /etc/postfix/main.cf on Debian-based operating systems:
```
That is not instructions to edit the `myhostname` field.
I read it as meaning `the changes you need to make are below`, and they are not.

**Comment by maxking** [comment]
Of you can open a Pull Request with what you think should be added to docs, I can add that?

**Comment by worikgh** [comment]
Fair enough.
Will do.
