### ISSUE TITLE
change the language

### ISSUE THREAD

**Issue by jalogisch** [maxking/docker-mailman#311]
I know that the core documentation does not include instructions in the documentation how to change the language ( https://mailman.readthedocs.io/en/latest/src/mailman/docs/internationalization.html#localization ) 

But if possible and known it would be gorgeous if that is short explained in this project - special as it might be different as with a 'normal' installation.

If I get a technical description, I'm willing to write that in a nice way - but I did not find something that explains in some kind of structured ways what needs to be done.

**Comment by maxking** [comment]
What do you want to change the language for? The web interface? The automated emails sent out?

**Comment by shoetten** [comment]
I would like to translate both, the web interface of Postorius (and HyperKitty as an added bonus) and the email templates. I could translate the later myself, of course, but it would be awesome to have a reference. German would be my particular need.

Unfortunately the documentation around localization seems to to be a little scarce.. Can you point me to the right direction? Thank you!

**Comment by maxking** [comment]
So, new versions of Postorius and Hyperkitty do ship with German translations (atleast, most of the strings are translated, newwer ones added are maybe not, but those aren't a lot). I think container build is missing `python manage.py compilemessages` in the entrypoint script, so they aren't easily available in the web ui. It needs to be documented somewhere how the [Web UI selects language.](https://docs.djangoproject.com/en/2.2/topics/i18n/translation/#how-django-discovers-language-preference). 

We have a Weblate project setup (https://hosted.weblate.org/projects/gnu-mailman/), but is still pending addition for 2 other projects( django-mailman3 and hyperkitty). We don't have automated push enabled for the repo, but I can download and update the translations manually when I get time. I do need to setup some sort of automatic pull-request style mechanism (as compared to automated push).

Core should also have German translations for email templates, however, the web interface doesn't have a way to set the language yet. You can do it from a command line shell. There is an [issue open for the same](https://gitlab.com/mailman/postorius/issues/303), I can help you out if you want to work on it.
