### ISSUE TITLE
mailman/config/schema.cfg missing

### ISSUE THREAD

**Issue by worikgh** [maxking/docker-mailman#312]
Apparently this file should be present.
[This message on the list](https://lists.mailman3.org/archives/list/mailman-users@mailman3.org/message/OZD46CM2G5ZYAVGVK6WWAS33T67MHOOU/) suggests it should be there

**Comment by maxking** [comment]
That file is inside the source code, it isn't required for deployment.

What Mark meant was that you can look at the file for an example on to change the server_owner's email address.

You can find a documented version of in our docs: https://mailman.readthedocs.io/en/latest/src/mailman/config/docs/config.html#schema-cfg
