### ISSUE TITLE
Please pull latest Hyperkitty

### ISSUE THREAD

**Issue by breti** [maxking/docker-mailman#315]
There are some issues with Hyperkitty and mySQL. Import of Mailman 2.1 lists is not functional. Please pull latest Hyperkitty version.

Please see

https://lists.mailman3.org/archives/list/mailman-users@mailman3.org/thread/O7Y2PBWK5VELT3P5AEPVXBI6R3CG2LWR/

https://gitlab.com/mailman/hyperkitty/issues/211

for details.

**Comment by shoetten** [comment]
Is there any reason not to bump to hyperkitty `1.2.2`? Otherwise i could make a quick PR.

**Comment by maxking** [comment]
No reason, PR would be great! Thanks.
