### ISSUE TITLE
README, NEWS and latest stable version

### ISSUE THREAD

**Issue by hrasmussendk** [maxking/docker-mailman#318]
The Docker installation understandably do not always follow new versions tightly. The docker-compose.yaml file for Docker Mailman currently say "maxking/mailman-core:0.2".

I am sure there is a good reason for this, but I've always wondered if using "latest" would always keep me up the latest stable Mailman version when a new one is released for Docker installation. On the other hand, I will be able to decide when to upgrade to a newer version when say "0.3" is released.

Some time ago I used rolling releases, but I presume this is not always the latest _stable_ version of Mailman, right?

The [NEWS.md](https://github.com/maxking/docker-mailman/blob/master/NEWS.md) is far behind and do not correspond with the version from tag 0.2. Could the [README-md](https://github.com/maxking/docker-mailman/blob/master/README.md#release) indicate the latest (stable) Docker installation tag like [Rolling Releases](https://github.com/maxking/docker-mailman/blob/master/README.md#rolling-releases) does?

**Comment by maxking** [comment]
So here is something undocumented right now about the tags:
- latest images are built using stable releases of each component, but are rebuilt on every commit. If I bump a version of a stable component in Core/Web, they get bumped when you pull `latest` next.
- 0.2 is the current stable head and should point to whatever 0.2.* is newest
- I wouldn't suggest using `rolling`, it is built from git master and is likely to break more often.

I have been pretty bad recently with documentation and release. There are a couple of new versions that I still need to package. I tried doing that last week and failed with funny errors where uwsgi is behaving weird (see #316) and hoping that they get updated soon.

I can still bump Core I guess, one off. 

NEWS.md is probably too stale, I should just remove it. I don't think I am keeping up with it. I *try* to tag releases in git and add a summary in Github about what changed, but I have been bad about that either :( You could continue to use 0.2 and that should give you the latest ones until 0.3 comes out.

I will update the README with the above information though, thanks very much for pointing it out.

**Comment by hrasmussendk** [comment]
Thanks for the explaination. I was unsure whether maxking/mailman-core:latest would be some kind of Mysql-version (from the name docker-compose-mysql.yaml) and that the current version of Progresql would be the maxking/mailman-core:0.2 (from the docker-compose.yaml).

When you say that latest will be rebuild on every commit, does that mean that they may be unstable?

Actually I try to understand what is best for me to have the latest stable version as soon as possible? Would that be the ```latest``` or the ```0.2```?

**Comment by maxking** [comment]
> I was unsure whether maxking/mailman-core:latest would be some kind of Mysql-version 

Images have actually nothing to do with databases, you can use any database with any image tags. The compose scripts are merely examples for people to base off their own scripts :) They are used for testing in this repo.

> When you say that latest will be rebuild on every commit, does that mean that they may be unstable?

No, they are built from every commit on this repo, not Mailman components. That means they use stable releases. But it is possible that I haven't tagged something and some extra setup scripts and settings that I have added in this repo might not exactly be fully stable.

> Actually I try to understand what is best for me to have the latest stable version as soon as possible? Would that be the latest or the 0.2?

I'd suggest using 0.2.
