### ISSUE TITLE
Usage of settings_local.py for mailman-web is broken

### ISSUE THREAD

**Issue by shoetten** [maxking/docker-mailman#322]
Currently the `settings_local.py` is copied from `/opt/mailman-web-data` to `/opt/mailman-web` as root in [docker-entrypoint.sh](https://github.com/maxking/docker-mailman/blob/master/web/docker-entrypoint.sh#L108).
This results in the file being owned by root, which in turn causes a Permission Denied error, because the unprivileged `mailman` user is not allowed to read.

Setting custom values for `EMAIL_HOST_USER`, `EMAIL_HOST_PASSWORD` and `EMAIL_USE_TLS` is thus impossible.

**Comment by maxking** [comment]
I'd have to check the mode of the file, even if the file is owned by root, it should be readable by others. If not, we should change that.

FWIW, I haven't seen problems reading `settings_local.py` in the testing instances that I have made before.

**Comment by shoetten** [comment]
I guess the mode gets carried over via the docker volume and the `cp` command (in contrast the the owner) and is therefore inherited from the original file. I don't really like the idea of a file with potentially sensitive values being world readable, though.

**Comment by maxking** [comment]
Well, it has to be readable by the `mailman` user. Maybe entrypoint script can chown/chmod file to make sure it is only readable by `mailman` user?

**Comment by shoetten** [comment]
Yeah, a simple chmod like you're doing [for the mailman-web-data dir](https://github.com/maxking/docker-mailman/blob/master/web/docker-entrypoint.sh#L143) should work fine.

**Comment by maxking** [comment]
Wait, there is a `-R` so it should already recursively chown the `settings_local.py` file.

**Comment by shoetten** [comment]
Yes, it does. But just in the `mailman-web-data` directory, not in the `mailman-web` dir. The `settings-local.py` file is copied once as root and then never touched again.

**Comment by maxking** [comment]
Yep, you are right.

**Comment by maxking** [comment]
Do you want to submit another pull request for that?

**Comment by shoetten** [comment]
Sure, [why not](https://github.com/maxking/docker-mailman/pull/324).
