### ISSUE TITLE
./manage.py runjobs minutely runs constantly with high load

### ISSUE THREAD

**Issue by k0a1a** [maxking/docker-mailman#327]
After importing existing lists and archives from Mailman 2 (about 200mb all together) 
> python3 ./manage.py runjobs minutely

runs all the time.

> CPU 95.7%  RAM 17.9%   0:27.55 python3 ./manage.py runjobs minutely

in `/opt/mailman-web-data/logs/uwsgi-error.log` i find the following:

> [uwsgi-cron] command "./manage.py runjobs minutely" running with pid 80 exited after 62 second(s)
Sat May  4 21:05:41 2019 - [uwsgi-cron] running "./manage.py runjobs minutely" (pid 85)
[uwsgi-cron] command "./manage.py runjobs minutely" running with pid 85 exited after 58 second(s)
Sat May  4 21:06:41 2019 - [uwsgi-cron] running "./manage.py runjobs minutely" (pid 87)
[uwsgi-cron] command "./manage.py runjobs minutely" running with pid 87 exited after 63 second(s)
Sat May  4 21:07:44 2019 - [uwsgi-cron] running "./manage.py runjobs minutely" (pid 89)
[uwsgi-cron] command "./manage.py runjobs minutely" running with pid 89 exited after 53 second(s)
Sat May  4 21:08:44 2019 - [uwsgi-cron] running "./manage.py runjobs minutely" (pid 91)

**Comment by maxking** [comment]
Can you try running:

```
docker exec -it mailman-web bash
python3 manage.py rebuild_index
```

This should build the index after the import went through?

**Comment by k0a1a** [comment]
About 6000 messages were re-indexed but `python3 ./manage.py runjobs minutely` is still running non-stop, the same after restarting mailman-web container.

Thanks

**Comment by danil-smirnov** [comment]
Guys I'm just curios: is this `runjobs minutely` is meant to be run minutely? I see the same behaviour in my list although with the logs showing significantly lesser time of jobs:

**Comment by maxking** [comment]
Well, the reason is that `whoosh`, which is the default search backend in container images is kind of not a good solution. It is based on pure python and works only well in development and smal or tiny installation scenarios. 

With anything bigger than a few hundred emails, it chokes and causes this kind of bahavior. Mailman support xapian, elastic search and Solr search backends too, but there isn't setup in images to use that.

**Comment by brianemwd** [comment]
How hard than is it to get a more robost search backend in place and move away from Whoosh?

 

Have a great day!

 

Brian Carpenter

EMWD.com

brian@emwd.com

**Comment by maxking** [comment]
I would say not much, mailman-web already has `xapian-core` and `xapian-bindinds-python` installed.  All it needs is `xapian-haystack` to be installed form `pip` and then an update in configuration to use that.

https://github.com/notanumber/xapian-haystack

This should have more documentation on how to achieve that. I am happy to accept PR to add it to mailman-web container.

**Comment by k0a1a** [comment]
OK. I'm barely using archives, let alone search. 
Is it safe to just comment out some of the jobs in uwsgi.ini and set others to higher niceness? 
Say:

```
#Setup hyperkitty's cron jobs.               
#unique-cron = -1 -1 -1 -1 -1 ./manage.py runjobs minutely
#unique-cron = -15 -1 -1 -1 -1 ./manage.py runjobs quarter_hourly
#unique-cron = 0 -1 -1 -1 -1 ./manage.py runjobs hourly          
unique-cron = 0 0 -1 -1 -1 nice -n19 ./manage.py runjobs daily             
unique-cron = 0 0 1 -1 -1 nice -n19 ./manage.py runjobs monthly           
unique-cron = 0 0 -1 -1 0 nice -n19 ./manage.py runjobs weekly            
unique-cron = 0 0 1 1 -1 nice -n19 ./manage.py runjobs yearly      

```
       

Thanks!

**Comment by maxking** [comment]
Yes, you can move the minutely job to run hourly instead. Actually, I am considering doing that for the official images.

If you want to submit a PR, I can merge that. Basically, it would be something lile:

```
# Run the minutely job to update index only hourly for
# performance reasons.
unique-cron = 0 -1 -1 -1 -1 ./manage.py runjobs minutely
```
