### ISSUE TITLE
site-owner not setable 

### ISSUE THREAD

**Issue by y0va** [maxking/docker-mailman#329]
The `site-owner` email address from `schema.cfg` is not setable via the environment.  

Workaround would be to extract `schema.cfg` as seperate volume from the container.

**Comment by y0va** [comment]
In contrast to @issue-label-bot I would label this as feature-request.

**Comment by maxking** [comment]
You can set the site-owner using `mailman-extra.cfg` specified in the README. schema.cfg is basically as schema for configuration that you are allowed to set in mailman’s configuration files like mailman.cfg
