### ISSUE TITLE
Create a mechanism to run cron jobs inside of the containers

### ISSUE THREAD

**Issue by maxking** [maxking/docker-mailman#33]
mailman-web container needs some mechanism to run the cron jobs for Hyperkitty.

http://uwsgi-docs.readthedocs.io/en/latest/Cron.html

uwsgi has some interesting ideas about running cron in the uwsgi server and might be a better idea than actually running a cron inside mailman-web.

**Comment by almereyda** [comment]
I.e. @indiehosters' nextcloud uses a separate cron container, as in https://github.com/indiehosters/nextcloud/blob/master/docker-compose.yml#L39-L55

cc @pierreozoux

**Comment by maxking** [comment]
I don't want to add another container just to maintain cron jobs, especially because these jobs are tied to the Django project that is running in the mailman-web container. So, I would either have to share all the code across containers or provide access to docker.sock to the cron container which can then `docker exec` the cron tasks inside the web container. I don't like the idea of either of them.

This issue is kinda resolved in the latest master branch using Cron-Like functions in uwsgi.

**Comment by ishitatsuyuki** [comment]
This should be already implemented, although the implementation itself is not correct: see #87.

**Comment by maxking** [comment]
Yes, I think this issue is left open because of the documentation issue. I haven't documented anywhere how the jobs work.
