### ISSUE TITLE
[Question] Questions regarding Unrouteable address

### ISSUE THREAD

**Issue by TommyLike** [maxking/docker-mailman#341]
**Tag/version of Container Images** 0.2.3
I deployed the docker-mailman through the README document. but I met the issue that when sending email :
```
2019-08-08 20:00:06 H=mail-ot1-f53.google.com [209.85.210.53] F=<tommylikehu@gmail.com> rejected RCPT <postorius@tommylike.me>: Unrouteable addres
```
I guess I did not fully understand how to exim4 will route the email in background. Could someone help me on figure it out why this is happening?
This is what I have configured:
1. the containers are all deployed on my instance, let's say it's IP [159.138.26.163]
2. I have bought a domain name [tommylike.me] which will be resolved as [159.138.26.163]
3. I configured the mailman web env 'SERVE_FROM_DOMAIN' = tommylike.me
4. when I try to reset my my password, I can find I will get a email from "postorius@tommylike.me"
5. when reply, I will have this issue pasted as above.

Is this related to how to configure the hostname (fqdn) of the instance/containers ? Is there any document that can help on this?

**Comment by maxking** [comment]
You don't need to reply to the email coming from `postorius@foo` it is more appropriately named as `no-reply-@...` I guess :)

There should be URL in it to reset the password, why are you trying to reply?
