### ISSUE TITLE
[Question] Is there a repo for mailman deployment on kubernetes

### ISSUE THREAD

**Issue by TommyLike** [maxking/docker-mailman#343]
**Tag/version of Container Images**
Choose from: latest, rolling, 0.2, 0.2.*

I tried this docker-mailman on localhost and it works perfectly, I am wondering if there is a existing repo or project which helps us deployment mailman suit on kubernetes. thanks:)

**Comment by maxking** [comment]
No, there aren't any deployment configurations for k8s yet.

On August 19, 2019 9:03:47 AM UTC, Hu Sheng <notifications@github.com> wrote:
>**Tag/version of Container Images**
>Choose from: latest, rolling, 0.2, 0.2.*
>
>I tried this docker-mailman on localhost and it works perfectly, I am
>wondering if there is a existing repo or project which helps us
>deployment mailman suit on kubernetes. thanks:)
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/maxking/docker-mailman/issues/343

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
