### ISSUE TITLE
Upgrade to the new 0.3.0 release

### ISSUE THREAD

**Issue by brianemwd** [maxking/docker-mailman#349]
How do I upgrade to the latest 0.3.0 release? What tag should I be using in the below update instructions:

$ docker-compose stop
$ docker-compose rm
$ docker pull maxking/mailman-core:$tag
$ docker pull maxking/mailman-web:$tag
$ docker-compose up -d

Also how do we move to using Xapian with your Docker container?

Thanks,
Brian

**Comment by maxking** [comment]
The update wasn't ready yet, I am going to work on that today.

Xapian core and python bindings are already installed in the images, all that is needed is the right configuration. I do need to spend some time to figure out if it works. If you want to try things out yourself before I can get to it, there is https://django-haystack.readthedocs.io/en/master/tutorial.html#xapian documentation in Django-haystack for the configuration needed.

**Comment by maxking** [comment]
Just made a release for 0.3.0
