### ISSUE TITLE
[BUG] Hyperkitty Bug

### ISSUE THREAD

**Issue by brianemwd** [maxking/docker-mailman#354]
**0.3.0**
I am seeing the following error being repeated every 2 seconds in the
uwsgi-error.log:

01:22:05 [Q] INFO Process-1:19112 processing [compute_thread_positions]
01:22:05 [Q] ERROR Failed [compute_thread_positions] - 'DiGraph' object has no attribute
'node' : Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django_q/cluster.py", line 381, in worker
    res = f(*task['args'], **task['kwargs'])
  File "/usr/lib/python3.6/site-packages/hyperkitty/tasks.py", line 127, in
_compute_thread_positions
    compute_thread_order_and_depth(thread)
  File "/usr/lib/python3.6/site-packages/hyperkitty/lib/analysis.py", line 55, in
compute_thread_order_and_depth
    walk_successors(thread.starting_email.id)
  File "/usr/lib/python3.6/site-packages/hyperkitty/lib/analysis.py", line 37, in
walk_successors
    obj = graph.node[msgid]["obj"]
AttributeError: 'DiGraph' object has no attribute 'node'

I was told to do the following:
"See https://gitlab.com/mailman/hyperkitty/issues/268
fixed by
https://gitlab.com/mailman/hyperkitty/merge_requests/201.

You need to change 'graph.node' to 'graph.nodes' at both line 37 and
line 44 in /usr/lib/python3.6/site-packages/hyperkitty/lib/analysis.py
to accomodate networkx >= 2.0"

However I can't find "/usr/lib/python3.6/site-packages/hyperkitty/lib/analysis.py" with the Docker setup.

**Comment by brianemwd** [comment]
Ok, so version 3.3.1 fixes the node bug. Now a new bug shows up, I think. The following shows up every few moments in the uwsgi-error.log:

13:15:42 [Q] INFO Process-1:910 pushing tasks at 1126
Process Process-1:910:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/site-packages/django_q/cluster.py", line 300, in pusher
    task = SignedPackage.loads(task[1])
  File "/usr/lib/python3.6/site-packages/django_q/signing.py", line 31, in loads
    serializer=PickleSerializer)
  File "/usr/lib/python3.6/site-packages/django_q/core_signing.py", line 38, in loads
    return serializer().loads(data)
  File "/usr/lib/python3.6/site-packages/django_q/signing.py", line 44, in loads
    return pickle.loads(data)
AttributeError: Can't get attribute 'unlock_and_call' on <module 'hyperkitty.tasks' from '/usr/lib/python3.6/site-packages/hyperkitty/tasks.py'>
13:16:42 [Q] ERROR reincarnated pusher Process-1:910 after sudden death

**Comment by maxking** [comment]
I think this issue is due to some pending tasks in the qcluster, which can't be processed due to a change in the object code.

I don't think any of the tasks are going to hurt if you just flush them, they are mostly meant to do text indexing and cron jobs to pull details from Mailman (which will work even if a new job comes in). 

You seem to have a lot of pending tasks, which should have been processed before. I admit such a scenario wasn't taken care of when changing how the tasks are processed. 

You should be able to clear all the old tasks from database. You can visit the `/admin` console and then remove the pending entries.

**Comment by brianemwd** [comment]
I am unable to delete any queued processes via the admin console. When clicking on Queued tasks in the Django Q section, the above exception that I quoted is generated: "AttributeError: Can't get attribute 'unlock_and_call' on". Is there another way to flush these pending tasks?

**Comment by maxking** [comment]
Can you just use sql to flush the database in that case?

**Comment by brianemwd** [comment]
I would if I knew how. Please provide directions on how to flush those ghost pending tasks.

**Comment by brianemwd** [comment]
Can I please get some assistance here? I cannot access the pending request page without throwing the above exception mention. I have another issue showing up with failed tasks but I would like to get this pending task problem fixed first. All of this started happening after upgrading to 3.3.1.

**Comment by maxking** [comment]
You can enter the container first:
```
$ docker exec -it mailman-web bash
```
Enter the Django's shell:

```
$ ./manage.py shell
```
And then finally, delete all the pending task:
```
>>> from django_q.models import OrmQ                                                                                                                                                     
>>> OrmQ.objects.all().delete()                                                                                                                                                          (0, {'django_q.OrmQ': 0})
```

This should clean up all the pending tasks in the queue.
