### ISSUE TITLE
Disable no-subject rule

### ISSUE THREAD

**Issue by jecal22** [maxking/docker-mailman#369]
I have spent many hours over the past few months trying to figure out how to disable the no-subject rule that holds incoming messages with no subject header.  I have searched the database tables, config files, and exhaustively searched Google for anything, but all I can find is the generic documentation about the no-subject rule, but nothing on how this rule is actually used within the docker-mailman suite.  Can anyone provide any insight into this?  It would be very nice if these default rules could be easily managed through the web interface.

Thanks in advance.

**Comment by maxking** [comment]
Please report this upstream at https://gitlab.com/mailman/mailman/issues, this is not an issue related to docker images.
