### ISSUE TITLE
[BUG] Postorius images mismatch

### ISSUE THREAD

**Issue by danil-smirnov** [maxking/docker-mailman#372]
There is latest images mismatch for Postorius images.

The bugfix from [PR 360](https://github.com/maxking/docker-mailman/pull/360) has been applied to `maxking/postorius:latest` image only and missed in `maxking/postorius:0.3` and `maxking/postorius:0.3.2` images.

I suppose we should have bug free 0.3 and 0.3.2 images for Postorius as well.

**Comment by maxking** [comment]
Thanks, I'll try making a 0.3.3 release. I probably should revert or tag a release without changing the default search engine in the images.
