### ISSUE TITLE
How to set default list settings

### ISSUE THREAD

**Issue by accessone67** [maxking/docker-mailman#373]
Hello 

How can I set the default settings for all newly created lists? Mailman doc say that I need to edit mm_cfg.py but I cant find this file no where in containers.

https://wiki.list.org/DOC/4.21%20Why%20make%20changes%20in%20mm_cfg.py%20NOT%20Defaults.py%20%3F

I have many lists to make and I dont want to configure them all individually. I wold like to make default settings to all the new created lists.

-----
sorry its not bug but question, but I cant change it anymore.

**Comment by maxking** [comment]
These containers are for Mailman 3, not Mailman 2. 
Unforntunately, there isn't a way to save a MailingList configuration as default for the server without modifying the source code. There are couple of styles defined and you should be able to set that in the `mailman.cfg`.
