### ISSUE TITLE
Remove Sign Up button

### ISSUE THREAD

**Issue by accessone67** [maxking/docker-mailman#377]
Hello

I'm using maxking/mailman-web:latest and I want to remove sign up button from webui, how can I do this? have not fond any way to do this.

Thanks.

**Comment by maxking** [comment]
With new release after 0.3.12, basically in django-mailman3 1.3.7, you can do this to disable signups: https://docs.mailman3.org/en/latest/faq.html?highlight=disable%20signup#how-to-disable-signup
