### ISSUE TITLE
[BUG] Dropdowns not working and throwing Popper.js error

### ISSUE THREAD

**Issue by bloomvdomino** [maxking/docker-mailman#386]
**Tag/version of Container Images**
latest

On the `latest` and at the `0.3` tag, the dropdowns are refusing to work. Clicking on them producing the error `Uncaught TypeError: Bootstrap dropdown require Popper.js`. Obviously the Popper.js library isn't loaded…

Maybe I'm missing something, but I think I have configured all things right…

**Comment by danil-smirnov** [comment]
@bloomvdomino Ctrl-F5?

**Comment by bloomvdomino** [comment]
> @bloomvdomino Ctrl-F5?

Yes. Even multiple times; also tried Incognito and at an other PC. Same behavior…

**Comment by bloomvdomino** [comment]
It works now!
