### ISSUE TITLE
[BUG] Mails go to shunt queue

### ISSUE THREAD

**Issue by danil-smirnov** [maxking/docker-mailman#399]
**Tag/version of Container Images**
Core 0.3.7

The latest Mailman Core image is broken due to
https://gitlab.com/mailman/mailman/-/issues/743

In case of DMARC mitigation is enabled, all mails from domains with DMARC record go to a shunt queue.

I'm not aware of any workaround except patching of Mailman Core with the following fix:
https://gitlab.com/mailman/mailman/-/commit/022c127ca87b45abf4486e62362aae4482aec8a4

**Comment by maxking** [comment]
Thanks for the repo, I forgot about this one. I’ve created an PR #400  to fix this. Will make a release once the PR passes CI and is merged.

**Comment by danil-smirnov** [comment]
@maxking Thank you for the quick response, the PR might not work until it is `dnspython\<2.0 \` rather than `dnspython<2.0 \`

**Comment by danil-smirnov** [comment]
Sorry @maxking but I believe the fix won't work. Please check CI logs

**Comment by maxking** [comment]
Thanks @danil-smirnov for pointers, I’ve added it in quotes to work around the shell redirection issue. I am not sure why Circle CI build worked. Something seems wrong with CI config.
