### ISSUE TITLE
Rolling release out of date on docker hub

### ISSUE THREAD

**Issue by richardbrinkman** [maxking/docker-mailman#406]
The rolling release seems not to be uploaded to Docker hub anymore. Doing a 

```sh
git pull maxking/mailman-core:rolling
docker image ls
```
reveals a 19 months old image. Whereas the quay.io/maxking/mailman-core image is less than a day old. So it appears that the building of the rolling release works but the uploading it to hub.docker.com (or docker.io) fails.

**Comment by maxking** [comment]
Looks like the access token for Dockerhub had expired. I have updated the token and the next build should push an updated release.

Thanks for the report!

**Comment by maxking** [comment]
This should now be fixed and a new version was just pushed to Dockerhub.
