### ISSUE TITLE
[BUG] Sample MySQL docker-compose-mysql.yaml Results in Non-Supported Configuration (no utf8mb4)

### ISSUE THREAD

**Issue by mistermatt2u** [maxking/docker-mailman#419]
** latest, 0.3, 0.3.* **

The docker-compose-mysql.yaml file imports the MariaDB 10.3 docker container from dockerhub. In MariaDB 10.3, the default character set is latin1, which is not recommended for Mailman (or in general). Under (at least) MariaDB 10.5, the default database character set was changes to utf8mb4, which is recommended for use with Mailman.

It seems like the following should occur in order to maximize the chances that docker-mailman will work correctly when using MySQL/MariaDB:

- Change the MariaDB version in docker-compose-mysql.yaml to 10.5 (or possibly "latest")
- Update database string for core in docker-compose-mysql.yaml to append: ''?charset=utf8mb4&use_unicode=1"
- Update documentation to give procedure for updating web configuration to use utf8mb4. It appears that it is not as simple as appending "?charset=utf8mb4&use_unicode=1" to the web database string in the yaml file. I had to put a whole database configuration section in the settings_local.py file, including the "'OPTIONS': {'charset': 'utf8mb4'}" part, in order to successfully override the database string in the yaml file. But perhaps there is a more direct way to do this within the yaml file.
- Perhaps update documentation to consolidate best practice guidance for the MySQL/MariaDB database use case. There are a few different places where the utf8mb4 recommendation/limitation is noted or discussed. [Here](https://mailman.readthedocs.io/en/stable/src/mailman/docs/database.html#mysql) (currently says utf8, needs to be updated), [here](https://lists.mailman3.org/archives/list/mailman-users@mailman3.org/thread/KNBJQIW3F2WZN3555PF25XFD3JZLXB7W/), and [here](https://gitlab.com/mailman/mailman-suite/-/blob/master/mailman-suite_project/settings.py#L156). 

This report is a result of an effort to bring the latest version of Mailman3 online using docker-mailman with MariaDB. Creating an installation as it is currently published, results in non-trivial issues with hyperkitty archiving and importing of Mailman2 archives, due to the character set limitations of latin1, which is the default in not so old versions of MySQL and MariaDB. Lots and lots of Django errors, server errors in the hyperkitty interface when loading messages, "loading icon" staying forever, errors on the console during mm2 archive import, etc.

I went thru the unfortunate process of having to rebuild the database after having already migrated to mailman3, due to this issue. But I was able to successfully resolve the charset related issues by moving to MariaDB 10.5. Hoping this will help others avoid that situation.

**Comment by maxking** [comment]
Thanks for such a detailed bug report and your investigations.
> * Change the MariaDB version in docker-compose-mysql.yaml to 10.5 (or possibly "latest")
I think it is okay to jump to 10.5, I don’t like “latest” because it is always a moving target.

Other suggestions do make sense, I think we should default to a more supported charset. Would you be willing to open a pull request with your suggestions?

**Comment by mistermatt2u** [comment]
@maxking I am not very well practiced with git; but I would like to give the PR a go. I'll try to do it this week. Thanks for your response.

**Comment by maxking** [comment]
I tried it out in the terminal and seems like adding `?charset=utf8mb4&use_unicode=1` to the DATABASE_URL worked for mailman-web too, translating it back to how Django's database configuration looks.

```
>>> DATABASES=config(default='mysql://myuser:mypassword@mymysqlhost/mailman?charset=utf8mb4&use_unicode=1')
>>> print(DATABASES)
{'NAME': 'mailman', 'USER': 'myuser', 'PASSWORD': 'mypassword', 'HOST': 'mymysqlhost', 'PORT': '', 'CONN_MAX_AGE': 0, 'OPTIONS': {'charset': 'utf8mb4', 'use_unicode': '1'}, 'ENGINE': 'django.db.backends.mysql'}
```

**Comment by mistermatt2u** [comment]
@maxking Sorry I didn't get to this before you. Thanks so much for fixing it up. I thought I tried passing the options in the DATABASE_URL didn't work for mailman-web; but I can't remember exactly how I tested. It may not even be necessary since the server charset and collation are set explicitly now. Perhaps some others will chime in as they test. Thanks again.

**Comment by maxking** [comment]
Closing this since we have updated the default configuration to use utf8mb4.
