### ISSUE TITLE
Error: no containers to start

### ISSUE THREAD

**Issue by fsantiago07044** [maxking/docker-mailman#42]
Hello. Installed docker and compose as instructed on centos 7. Left it in its default loop storage mode just for testing. Cloned your GitHub and starting the docker produces:

Starting database ... done
Starting mailman-core ... done
Starting mailman-web ... done
ERROR: No containers to start

What have I missed?

**Comment by maxking** [comment]
I am not exactly sure but I _think_ that this is because the docker-compose does not build the containers anymore it cannot find the images.

Can you try these commands and then again run `docker-compose up -d` ?
```
$ docker pull maxking/mailman-core:latest
# docker pull maxking/mailman-web:latest
```

**Comment by ulrith** [comment]
Are you sure you need to have
`docker-compose start`
instead of
`docker-compose up`
?

**Comment by maxking** [comment]
`start` is used to run existing containers [1](https://docs.docker.com/compose/reference/start/). When you run them for the first time, or when you update the images, you need to create the new ones using `up -d`.

**Comment by ulrith** [comment]
I understand, but the section 'Running' in the README.md - it's about the first time, right? If you creating directories there you should use 'up' then...

**Comment by maxking** [comment]
@ulrith Oh! I am so sorry, I misread your comment. Yes, you are right, I am going to fix that right away.

Thanks!
