### ISSUE TITLE
Upgrading

### ISSUE THREAD

**Issue by tpnsolutions** [maxking/docker-mailman#432]
@maxking,

First off thanks for creating and maintaining this amazing docker image for Mailman 3, your time on this is highly appreciated.

I know this is going to sound like a NOOB question, but I would appreciate your patience as I ask anyways.

Upgrading, what is the protocol between versions. More specifically, do I need to re-configure the "docker-compose.yaml" before executing an upgrade?

As I understand, the process for "installing" is something like this...

1. mkdir -p /opt/mailman/core
2. mkdir -p /opt/mailman/web
3. git clone https://github.com/maxking/docker-mailman
4. cd docker-mailman
5. make config adjustments to "docker-compose.yaml", "/opt/mailman/core/mailman-extra.cfg" and "/opt/mailman/web/local_settings.py" as documented
6. docker-compose up -d

What would be the steps for composing an upgrade?

Thanks again, I'm still wrapping my head around dockers images and just want to make sure I don't unintentionally break a Mailman installation while trying to keep it up to date.

Cheers!

Best Regards,
Peter Knowles | TPN Solutions

**Comment by mistermatt2u** [comment]
There is discussion about this in issue #293. Basically you would do something like below:

```
$ docker-compose stop
$ docker-compose rm
$ docker pull maxking/mailman-core:$tag
$ docker pull maxking/mailman-web:$tag
$ docker-compose up -d 
```
You would definitely want to retain the docker-compose.yaml file, as that should be customized to your installation (with passwords, etc). Depending on what version you are trying to upgrade to, yes you might want to change the $tag values in your docker-compose.yaml file. You would change it to whatever your target release is. However, you may not need to change it at all, if you are upgrading to the next point release. That is discussed [here](https://github.com/maxking/docker-mailman#release).

**Comment by maxking** [comment]
@mistermatt2u thanks for the steps and you are absolutely right about the steps.

We should be putting your comment somewhere in the readme for upgrades.
