### ISSUE TITLE
Please update aiosmtpd to 1.4.1 or newer in the images.  

### ISSUE THREAD

**Issue by matsmats-uw** [maxking/docker-mailman#442]
**Tag/version of Container Images**
container tag: 0.3

Please update aiosmtpd to 1.4.1 or newer in the images.  
 
This addresses https://gitlab.com/mailman/mailman/-/issues/836

thanks, steve

**Comment by maxking** [comment]
This was automatically fixed by a rebuild. It hasn't yet been released though, i'll try to tag a release soon.

**Comment by maxking** [comment]
Should be done with 0.3.12 images.
