### ISSUE TITLE
Hyperkiitty import Mailman 2.1 archives

### ISSUE THREAD

**Issue by gholman** [maxking/docker-mailman#445]
Is there a way with the Mailman 3 in Docker containers to import .mbox archives?

As per:  https://docs.mailman3.org/projects/hyperkitty/en/latest/install.html#importing-the-current-archives
However, Running django-admin --help in mailman-web container shows the hyperkitty_import command is not available.  

Is this functionality implemented or is there another way to import archives?

Thank you -

**Comment by maxking** [comment]
Try running `python manage.py hyperkitty_import --help` inside the mailman-web container. It should work.

django-admin requires you to setup settings correctly, and then it will work too.

**Comment by maxking** [comment]
Closing due to invactivity.
