### ISSUE TITLE
Templates folder empty in latest docker image

### ISSUE THREAD

**Issue by dieortin** [maxking/docker-mailman#462]
According to the documentation, the message templates should be in `/opt/mailman/core/var/templates`, but that directory is completely empty. Yet the container must be getting its templates somewhere, because the english ones work (I want to use the spanish ones)

How can I make sure mailman uses the spanish templates? I already set `[mailman] default_language: es`, but it has only affected the message subjects, and not the content.

Thanks for your time!

**Comment by maxking** [comment]
The "default" templates are in the source code of the package. If you want custom templates, you can set your template at `/opt/mailman/core/var/templates/lists/<list-id>/<lang>/list:member:regular:footer.txt`. Repleace `<list-id>`, `<lang>` and the name of the template appropriately.

**Comment by dieortin** [comment]
Thanks a lot for the response!

Is it possible to change the default templates for all lists? I'm not sure why, but only the subject of the e-mails is being translated, and not the body. 

Sorry if this isn't the appropriate channel for this kind of questions!

**Comment by maxking** [comment]
You can actually override it per-list, per-domain or for the entire site. 

For domains, `var/templates/domains/<domain>/<lang>/` and for site, `var/templates/site/<lang>`.

**Comment by dieortin** [comment]
This fixed my issue at last, I had added the templates directly to '/var/templates/<lang>/' instead of to '/var/templates/site/<lang>'. Thanks!
