### ISSUE TITLE
Environment variable ignored

### ISSUE THREAD

**Issue by omnitec** [maxking/docker-mailman#478]
With a key string in mailman-extra.cfg:
HYPERKITTY_API_KEY = 'random character string'

The config file is loaded:
mailman-core    | Found configuration file at /opt/mailman/mailman-extra.cfg

Yet the key is ignored:
mailman-core    | HYPERKITTY_API_KEY not defined, please set this environment variable...
mailman-core    | exiting...

Are there special requirements for HYPERKITTY_API_KEY other than a random character hash?

**Comment by omnitec** [comment]
Just found out that more environment variables are getting ignored:

SERVE_FROM_DOMAIN='FQDN'
MAILMAN_ADMIN_EMAIL='somebody@somewhere.org'

What's the secret to getting then parsed?

**Comment by maxking** [comment]
You want to set the `HYPERKITTY_API_KEY` in `docker-compose.yaml` file instead of `mailman-extra.cfg`.  See an example of this here https://github.com/maxking/docker-mailman/blob/main/docker-compose.yaml#L19

**Comment by omnitec** [comment]
Still having a problem with SERVE_FROM_DOMAIN: It is ignored, causing the Postorius password reset emails to show a host of <container IP>:8000.

Is that a separate variable?
