### ISSUE TITLE
[BUG] Postorius rolling image: issue with mailmanclient

### ISSUE THREAD

**Issue by danil-smirnov** [maxking/docker-mailman#482]
While playing with rolling deployments, I've discovered Postorius rolling image issue: `mailmanclient` comes out of sync with the Postorius, because it's not explicitly added to the Dockerfile and is being installed as a Postorius dependency:
https://github.com/maxking/docker-mailman/blob/main/postorius/Dockerfile.dev#L22

A correct approach, I suppose, would be to add `mailmanclient` into to Postorius image via the same pattern, as for Hyperkitty image:
https://github.com/maxking/docker-mailman/blob/main/web/Dockerfile.dev#L26

**Comment by maxking** [comment]
Can you open a PR for this? I think it makes sense to use the latest mailmanclient from git instead of installed one.

**Comment by danil-smirnov** [comment]
@maxking Created the PR:
https://github.com/maxking/docker-mailman/pull/486

I've made two more fixes in there:
- django-mailman3 from master as well
- bumped django to the same version as for hk image

I see that tests are green, but I didn't test the image by myself.

**Comment by maxking** [comment]
Closed by #486
