### ISSUE TITLE
[FEATURE] Please add ARM64 containers to docker hub.

### ISSUE THREAD

**Issue by colindawson** [maxking/docker-mailman#483]
**Tag/version of Container Images**
Choose from: latest

I have a kubernetes cluster running on ARM CPU's with 28 cores and 56GB ram.  You guys already have builds in place to product X86 images, it would be fantastic to be able to produce ARM64 images at the same time, so that people who are running on ARM based hardware can work with it.

I'd love to be able to deploy this to my cluster.  And I'm very sure that lots of people would like to be able to deploy using docker running on arm hardware (this could even include the M1 macs, though I'm not 100% sure of the build requirements for M1)

**Comment by colindawson** [comment]
I've used the information in this link https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/ to create a pull request that should allow multi arch builds to be done easily.

I've created a pull request that looks like it will work once experimental features have been enabled in your docker install.  
Here's the pull request #484

**Comment by simonjduff** [comment]
Similarly for Raspberry Pi
