### ISSUE TITLE
Get MAILMAN_WEB_SOCIAL_AUTH from environment 

### ISSUE THREAD

**Issue by manureini** [maxking/docker-mailman#491]
Hello,

AFAIK using `MAILMAN_WEB_SOCIAL_AUTH=[]` in the docker-compose file does not have any effect.
It would be great, if social auth could be disabled (or modified) via docker-compose file.

**Comment by maxking** [comment]
Converting env vars to Python lists is slightly tricky, it works well for single value settings, but for something like lists and dicts, it gets complicated. 

We could potentially explore some way to do it via a csv, that I have seen some other projects use, but I am not too sure if that would be good usability with long csv names of social account providers.

**Comment by manureini** [comment]
For my usage I just want to disable all providers. But I think a more general solution would be great.
I'd say csv is better than noting ;)

**Comment by maxking** [comment]
If you are willing to work on a PR, we can try using csv for it.

**Comment by manureini** [comment]
ok i played around a little bit and realized, that it's a bit tricky to remove the social login stuff.
I found https://lists.mailman3.org/archives/list/mailman-users@mailman3.org/thread/DWES57FVMWBSVXXPMVUDZ7FIB4ZAFRTO/
and I was able to resolve my issue with using a the `settings_local.py` which looks like this:

```python
INSTALLED_APPS = [
    'hyperkitty',
    'postorius',
    'django_mailman3',
    # Uncomment the next line to enable the admin:
    'django.contrib.admin',
    # Uncomment the next line to enable admin documentation:
    # 'django.contrib.admindocs',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_gravatar',
    'compressor',
    'haystack',
    'django_extensions',
    'django_q',
    #  'allauth',  this will disable the social accounts. Keep other social configs 
    'allauth.account',
    'allauth.socialaccount',
]
```

I assumed that deleting all values in `MAILMAN_WEB_SOCIAL_AUTH` will disable all social logins, but in my tests this does not have any effect anyway.
-> I think a csv is not needed. The `settings_local.py` is fine, too ;)

**Comment by maxking** [comment]
> I assumed that deleting all values in MAILMAN_WEB_SOCIAL_AUTH will disable all social logins, but in my tests this does not have any effect anyway.

It should do that, but note that you want to use 0.4.0 tag for that purpose.

This is where we define it: https://github.com/maxking/docker-mailman/blob/main/web/mailman-web/settings.py#L414

When you override INSTALLED_APPS in your settings_local.py, it has the same effect of overriding MAILMAN_WEB_SOCIAL_APPS = [] + DEFAULT_APPS (which has all the non-social django apps).
