### ISSUE TITLE
[BUG] settings.py is not copied

### ISSUE THREAD

**Issue by JonnyTischbein** [maxking/docker-mailman#501]
**Tag/version of Container Images**
Choose from: latest (main) f389cb0f583817f9fac69da68e960814ab9273ad

The web container entrypoint just copies the `settings_local.py` and not the `settings.py`
https://github.com/maxking/docker-mailman/blob/66dc40f9ae73960be2febd8f668983d91b4bca47/web/docker-entrypoint.sh#L110-L118

So the variable about the social accounts and installed apps, are not applied:
https://github.com/maxking/docker-mailman/blob/66dc40f9ae73960be2febd8f668983d91b4bca47/web/mailman-web/settings.py#L412-L414

```
$> docker-compose exec mailman-web /bin/bash
bash-5.0# python3 manage.py print_settings
[...]
INSTALLED_APPS                           = ['hyperkitty', 'postorius', 'django_mailman3', 'django.contrib.admin', 'django.contrib.auth', 'django.contrib.contenttypes', 'django.contrib.sessions', 'django.contrib.sites', 'django.contrib.messages', 'django.contrib.staticfiles', 'rest_framework', 'django_gravatar', 'compressor', 'haystack', 'django_extensions', 'django_q', 'allauth', 'allauth.account', 'allauth.socialaccount', 'django_mailman3.lib.auth.fedora', 'allauth.socialaccount.providers.openid', 'allauth.socialaccount.providers.github', 'allauth.socialaccount.providers.gitlab', 'allauth.socialaccount.providers.google']
[...]
```
So the socialaccount providers are still enables, even though I disables them in my `settings_local.py`.
```
$> cat web/settings_local.py 
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'xxxxxxxxx'
EMAIL_PORT = 25

SOCIALACCOUNT_PROVIDERS = {}

MAILMAN_WEB_SOCIAL_AUTH = []

DEBUG = True
```

**Edit**: As a workaround I can copy the `DEFAULT_APPS` as `INSTALLED_APPS` into my `settings_local.py`

**Comment by maxking** [comment]
Try using the `rolling` tags and let me know if that works for you. 

I just tried it out with them and it seems to work for me
```
bash-5.0# python3 manage.py print_settings | grep INSTALLED_APPS
INSTALLED_APPS                           = ['hyperkitty', 'postorius', 'django_mailman3', 'django.contrib.admin', 'django.contrib.auth', 'django.contrib.contenttypes', 'django.contrib.sessions', 'django.contrib.sites', 'django.contrib.messages', 'django.contrib.staticfiles', 'rest_framework', 'django_gravatar', 'compressor', 'haystack', 'django_extensions', 'django_q', 'allauth', 'allauth.account', 'allauth.socialaccount']
```

**Comment by maxking** [comment]
Closing this ticket. I have tagged 0.4.0 release and it should allow settings MAILMAN_WEB_SOCIAL_AUTH in your settings_local.py
