### ISSUE TITLE
[BUG] POSTORIUS_TEMPLATE_BASE_URL not set in postorius only installation

### ISSUE THREAD

**Issue by charles-haynes** [maxking/docker-mailman#502]
**0.3.11**

If you deploy a postorius only release (a release that doesn't include hyperkitty) the variable `POSTORIUS_TEMPLATE_BASE_URL` isn't set causing an error to be thrown if you try to edit a template.

As a workaround, I created a `settings_local.py` that just contained

``` python
import os

POSTORIUS_TEMPLATE_BASE_URL =  os.environ.get('POSTORIUS_TEMPLATE_BASE_URL', 'http://mailman-web:8000')
```

**Comment by maxking** [comment]
This is already a part of the Postorius image config, https://github.com/maxking/docker-mailman/blob/main/postorius/mailman-web/settings.py#L343

This was also released as a part of 0.3.12. Closing this issue.
