### ISSUE TITLE
Optimize containers to decrease memory consumption

### ISSUE THREAD

**Issue by ghost** [maxking/docker-mailman#52]
It would be great if you can optimize containers images to decrease their memory consumption. Right after creation I see that mailman-core container occupies more than 500M of memory and mailnman-core takes about 200M.

**Comment by maxking** [comment]
This is something dependent on how mailman itself works. I understand that the resource usage is a bit much that you might expect, but containers don't add much overheads.

There was a discussion on mailman-users@mailman3.org about the memory consumption http://lists.mailman3.org/archives/list/mailman-users@mailman3.org/thread/N477226LXQXUK2BAFJIGOI4ISANQVPER/#L5SXILMJOXW7W4XPSIWF3EDMJLAVPYSW
