### ISSUE TITLE
[REQUEST] Please add documentation on upgrade process

### ISSUE THREAD

**Issue by nixsy** [maxking/docker-mailman#523]
According to the upgrade docs

https://docs.mailman3.org/en/latest/upgrade-3.2.html#post-upgrade

you are supposed to stop the web service and run a series of commands (compress/collectstatic/etc):

`(venv) $ mailman-web migrate`
`(venv) $ mailman-web compress`
`(venv) $ mailman-web collectstatic`
`(venv) $ mailman-web compilemessages`

How do you stop the service under Docker?  If I stop the container, then I cannot access the manage.py command.

**Comment by elyograg** [comment]
I was thinking the same thing ... "What do I do when a new version comes out of the images used by docker-compose to build the containers?"

I wonder if this is something that would be answered by general Docker knowledge ... I have very little of that.

The postgres image used to build the database container is quite old.  Would it be advisable to upgrade that to a 10.x version, and how would I do that if it is advisable?

**Comment by elyograg** [comment]
I got a closer look at the images available for postgres.  Although the version is old, that image was updated only a few days ago.  So maybe it's not all that outdated.

**Comment by elyograg** [comment]
I was pointed at upgrade instructions on the mailman3 mailing list.  They are in issue #293 and I hear they will be added to the documentation at some point.
