### ISSUE TITLE
[BUG] mailman-core: hyperkitty needs an update to version 1.2.0

### ISSUE THREAD

**Issue by AndreVolksdorf** [maxking/docker-mailman#527]
**Tag/version of Container Images**
Choose from: 0.4.*

New eMails are not being archived. 

```
Nov 03 15:32:31 2021 (24) Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mailman_hyperkitty/__init__.py", line 154, in _archive_message
    url = self._send_message(mlist, msg)
  File "/usr/lib/python3.8/site-packages/mailman_hyperkitty/__init__.py", line 210, in _send_message
    raise ValueError(result.text)
ValueError: <html><title>Auth required</title><body>
                    <h1>Authorization Required</h1><p>The archiver key is now
                     required to be sent over the Authorization HTTP header.
                     You need to upgrade the mailman-hyperkitty package to
                     1.2.0 or newer.
                    </p></body></html>
```

mailman-hyperkitty needs an update to version 1.2.0
Update the authentication to call Hyperkitty using the API key as a part of Authorization HTTP header instead of url parameter.

**Comment by robol** [comment]
I think this is related to the new behavior of sending the key via a header, which is present in Hyperkitty 1.3.5, and requires the mailman-hyperkitty plugin 1.2.0. The current Dockerfile in core/ depends on mailman-hyperkitty 1.1.0, instead. 

See https://gitlab.com/mailman/hyperkitty/-/issues/387 and the related commits in https://gitlab.com/mailman/mailman-hyperkitty/-/commit/df9cdc44dc59c7ed78097ef8f5ba3db46e7a92e9

I did a quick test by running `pip install mailman-hyperkitty==1.2.0` inside the mailman-core container, and that appears to fix it.

**Comment by robol** [comment]
> I was able to work around this by changing the docker-compose.yaml to use mailman-web:0.4.1.

That fixes the issue for me as well (if I use the tag in mailman-core, I think), and that's what I was doing before looking into this , but it's essentially equivalent to downgrading to the previous version.
