### ISSUE TITLE
[BUG] 400 Bad Request

### ISSUE THREAD

**Issue by c4lliope** [maxking/docker-mailman#531]
**Tag/version of Container Images**: `0.4`

400 response on:
* https://relay.assembled.app/postorius/lists/
* https://relay.assembled.app/
* https://relay.assembled.app/hyperkitty

Logs look normal; core pauses as the database container comes up, then connects on port 5432 and resumes running.

The logs for `mailman-web` end on:
```
mailman-web     |   Applying postorius.0011_auto_20191109_1219... OK
mailman-web     |   Applying postorius.0012_auto_20200420_2136... OK
mailman-web     |   Applying postorius.0013_auto_20201116_0058... OK
mailman-web     |   Applying postorius.0014_auto_20210329_2248... OK
mailman-web     |   Applying postorius.0015_auto_20210619_0509... OK
mailman-web     |   Applying postorius.0016_auto_20210810_2157... OK
mailman-web     |   Applying sessions.0001_initial... OK
mailman-web     |   Applying sites.0002_alter_domain_unique... OK
mailman-web     | [uWSGI] getting INI configuration from /opt/mailman-web/uwsgi.ini
```

I don't know of any other place that the 400 request would be logged on the server, but point me in the direction and I'll share as much of my environment as necessary.

This is blocking a large deployment, so help is gladly sought.

**Comment by c4lliope** [comment]
Server IP is: `23.92.30.77`
Domain is: `relay.assembled.app`

My `/etc/nginx/sites-enabled/default` is:
```

server {

   listen 443 ssl default_server;
   listen [::]:443 ssl default_server;

   server_name relay.assembled.app;
   location /static/ {
        alias /opt/mailman/web/static/;
   }

   location / {
           proxy_pass http://127.0.0.1:8000;
           proxy_set_header Host relay.assembled.app;
           proxy_set_header X-Forwarded-For 23.92.30.77;

   }
   ssl_certificate /etc/letsencrypt/live/relay.assembled.app/cert.pem;
   ssl_certificate_key /etc/letsencrypt/live/relay.assembled.app/privkey.pem;

}
```

Acquired LetsEncrypt public/private key pair using:
```
docker run -it --rm \
  --name certbot -v "/etc/letsencrypt:/etc/letsencrypt" \
  -v "/var/lib/letsencrypt:/var/lib/letsencrypt" \
  -p 80:80 \
  certbot/certbot certonly
```

**Comment by pgmillon** [comment]
Hi, make sure you have set SERVE_FROM_DOMAIN correctly to relay.assembled.app.
I had something similar when I had something different than the expected domain.
There's also the DJANGO_ALLOWED_HOSTS if needed.

**Comment by c4lliope** [comment]
Yes, this looks like a fix. Much obliged, @pgmillon.
