### ISSUE TITLE
[BUG] Logs not rotating

### ISSUE THREAD

**Issue by p3lim** [maxking/docker-mailman#535]
**Tag/version of Container Images**
0.3.\*, 0.4.\*

Logs are never rotated, we had mailman/wsgi logs that exceeded 100GB in total.

This should be fairly trivial to fix, just adding policies to /etc/logrotate.d and running logrotate in a cron job.

**Comment by maxking** [comment]
Containers don’t have a cron job, but we can do something about log rotation by configuring mailman-web/mailman-core or something.

**Comment by mistermatt2u** [comment]
Below is a script I placed in /etc/logrotate.d/mailman to address this issue. I believe this will rotate the logs every week, by default. You would need to confirm where your logs are stored, as that may be dependent on how you have configured your containers.

`# rotate logs for Mailman (Docker)
# logs are in various locations within /opt/mailman

"/opt/mailman/core/var/logs/*.log" {
postrotate
        docker-compose -f /opt/mailman/docker-mailman/docker-compose.yaml restart mailman-core
endscript
}

"/opt/mailman/web/logs/*.log" {
postrotate
        docker-compose -f /opt/mailman/docker-mailman/docker-compose.yaml restart mailman-web
endscript
}`

**Comment by jeensg** [comment]
Are there any news on this?
Just found my logs to be quite large after 2 years ... and don't know exactly on how to proceed with @mistermatt2u s suggestion.

**Comment by yaseppochi** [comment]
I'm not familiar with the current Docker setup, so it's possible rotation is not configured.  Even once it's configured, most likely
https://gitlab.com/mailman/mailman/-/issues/931
is also a problem.

**Comment by dehnert** [comment]
> I'm not familiar with the current Docker setup, so it's possible rotation is not configured. Even once it's configured, most likely https://gitlab.com/mailman/mailman/-/issues/931 is also a problem.

@mistermatt2u's workaround (restarting the container entirely) probably works regardless of that bug, though the container restart is a bit more invasive than would be ideal. (It looks like with `mailman-core` the Mailman#931-vulnerable command is probably `docker exec -u mailman mailman-core mailman reopen`, but I'm not sure for `mailman-web`.)

**Comment by dehnert** [comment]
I think it's pretty plausible that there's not really a great way to have the *containers* do the rotation themselves, but the docs could certainly mention "hey you might want to set up log rotation, here's a sample config", somewhat like they currently talk about MTA, web server, search indexing, TLS, etc..
