### ISSUE TITLE
Where can I find additional config files?

### ISSUE THREAD

**Issue by jlgarnier** [maxking/docker-mailman#540]
Hi all,

I've installed Mailman (mySQL db) and cannot find any mailman-extra.cfg / settings_local.py files. Should these files be created from scratch after the containers have been created or should docker-compose also install them?

In the first case, where can I find any example file? I want to configure mailman to send mails through the mail server provided by our hosting provider (OVH) and cannot see if the standard env variables in the docker-compose file are enough to perform this redirection.

Thanks in advance for any help!

**Comment by mistermatt2u** [comment]
@jlgarnier Those files need to be created as needed, I don't believe they are auto-created by the docker-compose or the container images. 

After the .4.0 series, my mailman-extra.cfg basically became empty. The only thing I configure in there now is:
`[mailman]
site_owner: postmaster@example.org`
Prior to .4.0, I also configured the MTA stuff. That is no longer needed in a default configuration, as the new containers automagically detect the IPs. If you want to override the MTA stuff, you can put the below in /opt/mailman/core/mailman-extra.cfg. Just override what you need to, such as the 'smtp_host' variable. Take out the rest of the lines.
`[mta]
incoming: mailman.mta.postfix.LMTP
outgoing: mailman.mta.deliver.deliver
lmtp_host: 172.19.199.2
lmtp_port: 8024
smtp_host: 172.19.199.1
smtp_port: 25
configuration: /etc/postfix-mailman.cfg`

You can set the mta (ie. postfix) in the docker-compose file, but I don't believe you can override the other stuff in there. I think you have to use mailman-extra.cfg to do it.

**Comment by maxking** [comment]
Thanks @mistermatt2u for the answer. Closing this, please reopen in case you have more questions.
