### ISSUE TITLE
[SUPPORT] Can't access admin web page

### ISSUE THREAD

**Issue by jlgarnier** [maxking/docker-mailman#541]
Hi Community,

I'm a complete beginner with this tool and just managed to create and run the containers as given by the docker-compose file. I fell however at lost when trying to use them:

- I can access mailman.mydomain.com but reach a very minimalist UI (as attached)
![image](https://user-images.githubusercontent.com/26840059/161749299-5b9e9df9-9c4e-4118-bf68-f3bf0719006b.png)
- I cannot log in as admin as I couldn't find the default login/password anywhere in the documentation.
- I couldn't find the additional config files (mailman-extra.cfg + settings_local.py) and didn't understand if I have to create them or if it's a failure during the container creation (already posted on this point).
- I'll probably have to ask for help for the MTA configuration, as I want to use our existing mail server (set up by our hosting provider as domain creation).

Mailman looks definitely quite complex to configure to me and the doc doesn't help much. Hope you'll grant pity to a newbie...

Thanks in advance for any help!

**Comment by jeensg** [comment]
Did you already fiond help?`Normally the mailing-list is the right place to ask for this kind of questions: https://lists.mailman3.org/archives/list/mailman-users@mailman3.org/ -> here you can check the archive and probably find soime answers.

- the first problem seems to be misconfiguration, missing "static"-part: ` mm-web:
...
     - UWSGI_STATIC_MAP=/static=/opt/mailman-web-data/static`
- for the second one, you need to create superuser in mm-web-container via python: `python3 manage.py changepassword $YOURUSER`
- for the extra-files, one need to copy these files extra in the container upon building, e.g. Dockerfile mm-core: `FROM maxking/mailman-core:0.4.2
COPY ./mailman-extra.cfg /opt/mailman/` -> this can be done differently, more you find here in the docs: https://asynchronous.in/docker-mailman/#configuration
- for the last point did you check here? https://github.com/maxking/docker-mailman#setting-up-your-mta

**Comment by jlgarnier** [comment]
Hi maxking and thanks for the follow-up! As I couldn't get the application to work as expected, I just gave up and found another tool.

Thanks again for your help!
