### ISSUE TITLE
maxking/mailman-web:latest is more than one year old

### ISSUE THREAD

**Issue by richardbrinkman** [maxking/docker-mailman#551]
A `docker pull maxking/mailman-web:latest` downloads a year old image. I expect this command to download the latest stable release. On https://github.com/maxking/docker-mailman/releases version 0.4.2 is tagged 'latest'. Why is there a difference between the latest docker image and the latest git release of docker-mailman?

This issue is a duplicate of #543. That issue was closed with the comment that it should be fixed. Since nothing was fixed and I could not reopen the original issue, I issue the same thing again. As a proof that the issue is still not fixed, check the last pushed date on https://hub.docker.com/r/maxking/mailman-web/tags

**Comment by joergmschulz** [comment]
there is a 0.4 that has been pushed 3 months ago: docker pull maxking/mailman-core:0.4

**Comment by joergmschulz** [comment]
so now there is something brand-new on docker.io / would you like to close this issue?

**Comment by richardbrinkman** [comment]
The latest tag is last pushed 2 years according to https://hub.docker.com/r/maxking/mailman-web/tags. This issue has not been resolved, so please leave this issue open until a new release is pushed to the latest tag.

**Comment by joergmschulz** [comment]
upstream has issued a new release .... https://docs.mailman3.org/projects/mailman/en/latest/src/mailman/docs/NEWS.html#news-3-3-7

**Comment by maxking** [comment]
Closing this since 0.4.5 was released recently.

**Comment by richardbrinkman** [comment]
Please reopen this issue, since it is not fixed at all. @maxking, please take a look at https://hub.docker.com/r/maxking/mailman-web/tags. It clearly shows that the 'latest' tag has been pushed 2 years ago.
It is now the second time that the issue (#543 and #551) is closed without fixing the actual issue.

Perhaps I was not clear enough. I did not raise the issue that the newest version is not released on hub.docker.com. My issue is that the 'latest' tag does not point to the newest (stable) version. In my opinion 'latest' should point (as of today) to 0.4.5 and when 0.4.6 comes out, repointed to 0.4.6.

**Comment by maxking** [comment]
I have stopped pushing to 'latest' tag, not sure what is the best way to convey that :-)

There are no references to 'latest' anymore in documentation (if there is something I am missing, we should get rid of that). 

If you want versions that are updated without bumping to each release, please use `0.4` instead which points to the latest 0.4.x. When we make a breaking release in the container images, we'll bump to 0.5 series when you'd want to make changes in your configs accordingly.

**Comment by joergmschulz** [comment]
couldn't you just remove the 'latest' from github?

**Comment by richardbrinkman** [comment]
Is there a reason not to publish the latest tag? All other Docker images I know of, including the Docker official images, publish the newest stable release with the latest tag.
I understand that using the latest tag and upgrading automatically, might break things, when there are backwards incompatible changes. But the same thing is true for images like php:latest. It should be the choice of the user to use the rolling release, latest stable version or a specific version.
