### ISSUE TITLE
Fine grained Social Media login button configuration

### ISSUE THREAD

**Issue by RanceH** [maxking/docker-mailman#553]
We seem to be inundated with OpenID related errors when bots, etc try to use social media login buttons that are not configured in the backend.

The docs state how to disable the social login button bar as a whole, but do not mention how to enable/disable specific buttons in the social login bar.

It confuses our users to show buttons that do not work.  If I'm missing something, please point me in the right direction.

**Comment by meneken17** [comment]
There was some discussion on the topic in #283

You should find all information about configuring the social logins starting here: https://docs.mailman3.org/en/latest/config-web.html#configure-social-login

**Comment by maxking** [comment]
Thanks @meneken17 for the answer! Closing this one, @RanceH please reopen in case it isn't clear.
