### ISSUE TITLE
[BUG] SMTP_HOST_PASSWORD, SMTP_HOST_USER used by mailman-web but not by mailman-core

### ISSUE THREAD

**Issue by joergmschulz** [maxking/docker-mailman#556]
**Tag/version of Container Images**
 0.4.*

While mailman-web perfectly uses the login credentials for an smtp user defined in the docker-compose.yml, mailman-core does not. 
Do we need to define these values in mailman-extra.cfg additionally/ a second time?

**Comment by maxking** [comment]
Yes, you need to define these in the mailman.cfg or mailman-extra.cfg file. See Core's documentation on how to do that.
