### ISSUE TITLE
Can't communicate with django

### ISSUE THREAD

**Issue by StevenP94** [maxking/docker-mailman#581]
Version 0.4.4 installed
when nginx calls http or uwsgi results in timeout.
telnet localhost give connected on both 8000 and 8080
w3m on http 8000 never reply
reinstalled from scratch a couple of times without success
tested with apache2 and nginx gives the same: error 500 or 502
any hints to troubleshooting?

I apologize for my english

**Comment by maxking** [comment]
Do you get any logs in stdout of the containers?
