### ISSUE TITLE
[BUG]DEFAULT_AUTO_FIELD errors

### ISSUE THREAD

**Issue by RanceH** [maxking/docker-mailman#595]
**Tag/version of Container Images**
Image v. 0.4

Got a log full of these kinds of log entries:
hyperkitty.ThreadCategory: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
	HINT: Configure the DEFAULT_AUTO_FIELD setting or the HyperKittyConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.

These come from modules of hyperkitty and postorius.

They appear to be related to this: [Default Auto Field](https://dev.to/weplayinternet/upgrading-to-django-3-2-and-fixing-defaultautofield-warnings-518n)

Not sure where to fix this, but I'm happy to help if I can.

**Comment by maxking** [comment]
Yeah, we probably just need to update the settings.py with the setting you mentioned.

**Comment by veixus** [comment]
yes, I just added : 
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField' to /opt/mailman/web/settings_local.py and the warning dissapeared
