### ISSUE TITLE
Upgrade from 0.4.3

### ISSUE THREAD

**Issue by s0ftcorn** [maxking/docker-mailman#603]
Since you cant simply replace version in the docker-compose.yml and pg_upgrade needs both versions to be present. What is the suggested upgrade path?

**Comment by duck-rh** [comment]
If i'm not mistaken unless you pinned it to patch-level versions it's even worse than that. The example uses `mailman-web:0.4` and you'll get sqlalchemy bumped which requires PG 11 and will refuse to start. Bumping image to 0.5 would have avoided that.

Anyway, I heard Fedora-based image have a mechanism, probably keeping the pg_dump of the old version around, but that's surely tied to Fedora releases so there's only one single old version, which is not our case here. So I guess the procedure here would be to stop all containers except the database, dump inside it, fetch the dump, stop it, move aside the db storage to start anew, update the image and restore the dump. That's a lot of manual steps though.
