### ISSUE TITLE
[Feature Request] Seperate mailman host definitions for mail man and postfix data files in mailman-core

### ISSUE THREAD

**Issue by cceaood** [maxking/docker-mailman#621]
For some background i'm most of the way through settings up mailman in kubernates (specifically k3s) using multi-container pods (eventually core,web and nginx will reside in a singular pod with the db being in a comon db pod), the incoming mail is going to be handled by an additional postfix pod however by default mailman will find the the cluster address where it is more  useful to have it bind to any/localhost (using MM_HOSTNAME) for container-container communication without having to expose the service unnecessarily the only  issue with is that the lmtp tables mailman generates are then using this address which is obviously unroutable  for the postfix pod.

If would be nice to have a second variable, say something like MM_HOSTNAME_TEMPLATE that I could set to the service name for the exposed lmtp service for this purpose.

So for example id set

MM_HOSTNAME=0.0.0.0
MM_HOSTNAME_TEMPLATE=mailman-80.default.svc.cluster.local

which would result in mailman binding to 0.0.0.0 (and thus being accessible to all containers in the pod on 127.0.0.1) but populate postfix_lmtp along the lines of this.

/^testlist@lists\.testdomain\.co\.uk$/                  lmtp:[mailman-80.default.svc.cluster.local]:8024
/^testlist-bounces(\+.*)?@lists\.testdomain\.co\.uk$/   lmtp:[mailman-80.default.svc.cluster.local]:8024
/^testlist-confirm(\+.*)?@lists\.testdomain\.co\.uk$/   lmtp:[mailman-80.default.svc.cluster.local]:8024
/^testlist-join@lists\.testdomain\.co\.uk$/             lmtp:[mailman-80.default.svc.cluster.local]:8024
/^testlist-leave@lists\.testdomain\.co\.uk$/            lmtp:[mailman-80.default.svc.cluster.local]:8024
/^testlist-owner@lists\.testdomain\.co\.uk$/            lmtp:[mailman-80.default.svc.cluster.local]:8024
/^testlist-request@lists\.testdomain\.co\.uk$/          lmtp:[mailman-80.default.svc.cluster.local]:8024
/^testlist-subscribe@lists\.testdomain\.co\.uk$/        lmtp:[mailman-80.default.svc.cluster.local]:8024
/^testlist-unsubscribe@lists\.testdomain\.co\.uk$/      lmtp:[mailman-80.default.svc.cluster.local]:8024

It would id think also make sense for MM_HOSTNAME_TEMPLATE to only be used if specificed and otherwise default to MM_HOSTNAME.

**Comment by maxking** [comment]
This is something that we'd need to solve in Core instead of container images, since that's where the transport files are created. I do remember this to be an issue, but not sure if one exists at gitlab.com/mailman/mailman/-/issues. Can you please create one there?
