### ISSUE TITLE
[BUG] Tag `latest` out of date

### ISSUE THREAD

**Issue by raph-topo** [maxking/docker-mailman#625]
**Tag/version of Container Images**: latest

On Docker Hub:

TAG
[latest](https://hub.docker.com/layers/maxking/mailman-core/latest/images/sha256-34b5c3af84cce9b3d3a758e12cb4edeabbc1559b4fba14cb85532471b5a0f199?context=explore)
Last pushed 2 years ago by [maxking](https://hub.docker.com/u/maxking)

whereas

TAG
[0.4](https://hub.docker.com/layers/maxking/mailman-core/0.4/images/sha256-b79618064c15b48f726857c1590ded58e97cd708b49309e2d32ca513c74ba32b?context=explore)
Last pushed 5 months ago by [maxking](https://hub.docker.com/u/maxking)

As such, `latest` is far out of date compared with `0.4`

**Comment by maxking** [comment]
See https://github.com/maxking/docker-mailman/issues/551 please. I don't publish `latest` anymore.

**Comment by raph-topo** [comment]
Thank you. 
There are guides out there that still use the `latest` tag…
