### ISSUE TITLE
[BUG] Package `tzdata` is missing

### ISSUE THREAD

**Issue by raph-topo** [maxking/docker-mailman#626]
**Tag/version of Container Images**
`latest´ as of today (34b5c3af84cc)
Confirmed in [0.4.5](https://hub.docker.com/layers/maxking/mailman-core/0.4.5/images/sha256-b79618064c15b48f726857c1590ded58e97cd708b49309e2d32ca513c74ba32b?context=explore) as well.

Package `tzdata` is missing as per Alpine-based image practice.

As such, image does not respect `TZ` env var.

### Workaround

Build:
```Dockerfile
FROM maxking/mailman-web:latest

RUN apk add --no-cache tzdata
```
And set `TIME_ZONE = ` in `settings_local.py` as well.

**Comment by raph-topo** [comment]
Confirmed in [0.4.5](https://hub.docker.com/layers/maxking/mailman-core/0.4.5/images/sha256-b79618064c15b48f726857c1590ded58e97cd708b49309e2d32ca513c74ba32b?context=explore) as well.

**Comment by raph-topo** [comment]
Indeed `web/Dockerfile` does contain `pip install tzdata` but that does not seem sufficient, adding via `apk` seems to be the only viable way.

**Comment by raph-topo** [comment]
Apparently, setting `TIME_ZONE = ` in `settings_local.py` is required as well…

**Comment by maxking** [comment]
Can you open a PR addding tzdata to apk packages in both web/dockerfile and web/dockerfile.dev.

Do note that #602 talks about postorius image and not mailman-web image.
