### ISSUE TITLE
[BUG] Some connections to MySQL database fail 

### ISSUE THREAD

**Issue by raph-topo** [maxking/docker-mailman#629]
**Tag/version of Container Images**
0.4.5

Using `mariadb:10.5` as configured in [docker-compose-mysql.yaml](https://github.com/maxking/docker-mailman/blob/main/docker-compose-mysql.yaml) works, but Docker logs for `database:` still spit out some mysterious lines:
```
[Warning] Access denied for user 'root'@'172.30.0.4' (using password: NO)
[Warning] Access denied for user 'root'@'172.30.0.3' (using password: NO)
[Warning] Aborted connection 5 to db: 'mailman' user: 'mailman' host: '172.30.0.3' (Got an error reading communication packets)
[Warning] Aborted connection 18 to db: 'mailman' user: 'mailman' host: '172.30.0.3' (Got an error reading communication packets)
[Warning] Aborted connection 28 to db: 'mailman' user: 'mailman' host: '172.30.0.3' (Got an error reading communication packets)
```

(`172.30.0.4` is `mailman-core` & `172.30.0.3` is `database`)

**Comment by maxking** [comment]
I am unsure what is causing this, probably need to run this with Mailman CI and see what's going on.
