### ISSUE TITLE
Allow creating a superuser from the environement vars

### ISSUE THREAD

**Issue by maxking** [maxking/docker-mailman#63]
It is possible to create a django supseruser from the commandline.

It would be a good idea to allow creating that using the environment vars the first time the `mailman-web` container runs.

https://docs.djangoproject.com/en/1.11/ref/django-admin/#createsuperuser
^
For reference to the command's docs.

**Comment by maxking** [comment]
https://djangosnippets.org/snippets/1875/

Something like this would also be cool to have.

**Comment by ishitatsuyuki** [comment]
This should be already resolved.

**Comment by maxking** [comment]
Fixed with #93
