### ISSUE TITLE
[BUG]Why are static resources found when the web page has no style

### ISSUE THREAD

**Issue by zhangyang-1** [maxking/docker-mailman#640]
**Tag/version of Container Images**
Choose from: rolling, 0.3, 0.3.*, 0.4.*
![image](https://github.com/maxking/docker-mailman/assets/32324916/d511e155-fb8a-4c42-a64c-bfab1867e6b8)

**Comment by zhangyang-1** [comment]
![image](https://github.com/maxking/docker-mailman/assets/32324916/59d256b3-b9a7-40bd-afb4-10e012c4b9a0)

**Comment by maxking** [comment]
I am not really sure about why this is happening, first time I am getting report of this. Are you following the provided compose file for deployment?

**Comment by simotrone** [comment]
I got the same problem: no web style.
But I see issues in the js console.
![2023-09-01-095528_1914x899_scrot](https://github.com/maxking/docker-mailman/assets/514688/f3a5d149-bf55-45cc-839a-fdd8083cc6c0)
