### ISSUE TITLE
Trouble upgrading to 0.4.

### ISSUE THREAD

**Issue by Kulturserver** [maxking/docker-mailman#648]
We tried upgrading from 0.3 to 0.4 with the following steps
- creating a dump of the Postgresql database mailmandb
- setting the images mailman-web and mailman-core in docker-compose.yaml from Version 0.3 auf Version 0.4:
    image: maxking/mailman-core:0.4
    image: maxking/mailman-web:0.4
- then updating postgresql: image: postgres:10.1-alpine
- deleting the directory /opt/mailman/database
- calling docker-compose up -d the new containers were received and started
- now the database dump was imported again

Looking at the log of the mailman-core-container, at the end the following error is shown:
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres 

What else is there to do? Any help would be appreciated, thanks!

**Comment by maxking** [comment]
Can you update `postgres` to `postgresql` in the DATABASE_URL?

With newer versions of sqlalchemy, I think 'postgres' is no longer valid.

**Comment by maxking** [comment]
Actually, that might not be the case. THe newer release will have that issue and it is still not out.

Can you send output of `docker images | grep mailman`?

**Comment by Kulturserver** [comment]
Sorry for the late reply, we didn't have time to try the update again. Here's the output:

REPOSITORY             TAG           IMAGE ID       CREATED        SIZE
maxking/mailman-web    0.4           3f0bc6a75e1e   8 months ago   248MB
maxking/mailman-core   0.4           e435fcfc7d03   8 months ago   204MB
maxking/mailman-web    0.3           9ba9d3d7084d   2 years ago    487MB
maxking/mailman-core   0.3           26c920c0094b   2 years ago    178MB
postgres               9.6-alpine    aa87de9a5e0f   5 years ago    39.2MB
postgres               10.1-alpine   e6c5e6a76255   5 years ago    38.2MB

**Comment by jakicoll** [comment]
Did you read the section about [upgrading to 0.4 in the NEWS.md](https://github.com/maxking/docker-mailman/blob/main/NEWS.md#upgrading-to-040-release)?

**Comment by almereyda** [comment]
Updating the scheme scheme in `DATABASE_URL` helped us.

Plus the behaviour seen in

- #614 

disappeared.

**Comment by maxking** [comment]
Closing this as fixed.
