### ISSUE TITLE
Mailman does not restart after system reboot

### ISSUE THREAD

**Issue by jakicoll** [maxking/docker-mailman#651]
If a server is rebooted, the mailman services needs to be started again by manual intervention.
For services like this, I usually configure the containers with `restart: always`.
Would you accept a PR adding that to the docker-compose files?

**Comment by maxking** [comment]
I'd prefer using 'unless-stopped' instead of 'always'. PR welcome :-)

**Comment by maxking** [comment]
Should be fixed by #663
