### ISSUE TITLE
NameError name 'os' is not defined.

### ISSUE THREAD

**Issue by fe-os-rz** [maxking/docker-mailman#660]
I get an error NameError name 'os' is not defined.
```
  File "/opt/mailman-web/settings.py", line 408, in <module>
    from settings_local import *
  File "/opt/mailman-web/settings_local.py", line 44, in <module>
    MAILMAN_REST_API_URL  = os.environ.get('MAILMAN_REST_URL', 'http://mailman-core:8001')
NameError: name 'os' is not defined
```
Similar errors occur, if SECRET_KEY is set yaml files.

Google-magic says:

_To summarise, the error “NameError: name 'os' is not defined” occurs when attempting to use the os module in Python without importing it first. To resolve this error, we need to import the os module at the beginning of your script or in the Python shell._

What can I do (working with 0.4 release).

**Comment by maxking** [comment]
In you `/etc/mailman3/settings_local.py` you want to add `import os` on the top of the file to resolve.

**Comment by maxking** [comment]
Let me know if the issue persists, closing this for now.
