### ISSUE TITLE
[Question] Customising Postorius theme

### ISSUE THREAD

**Issue by Encephala** [maxking/docker-mailman#661]
Hey! I'm using the `core` and `postorius` containers to migrate an existing barebones installation of Mailman to Docker. Thanks a lot for your work!

We have customised Postorius, using custom HTML/CSS/JS. I'm struggling to figure out how to get Postorius to use these. I'm fine with monkey-patching the container via a Dockerfile or a volume, but I can't get anything to work.
How should I go about this?

Specifically:
Django collects static files into the `static/` directory that gets mounted, so I can't manually add files there; the solution is to add the CSS/JS files in some directory and add this to `STATIC_DIRS` in `settings_local.py` right?

I've executed into the container and manually edited `/usr/lib/python3.10/site-packages/postorius/templates/postorius/base.html`, but I don't see these changes reflected on the page that gets rendered. As far as I can tell from `settings.py`, those are the templates that get used, so do you have an idea what could be happening? Is Django caching templates or something?

**Comment by maxking** [comment]
How have you customized it specifically? Can you add more details.

I see you have modified the base.html, but what else are you changing? Is it the CSS files?

**Comment by Encephala** [comment]
We have custom HTML templates and custom CSS:
![screenshot](https://github.com/maxking/docker-mailman/assets/29434548/2028fdf9-23dc-4018-94e0-a31a8778573e)

I believe I'm actually wrong in saying we customised any of the JS, but I'd imagine overwriting JS/CSS is the same process anyway

**Comment by Encephala** [comment]
Okay so I managed to get everything we needed working. For anyone running into this, here's what we did. It isn't necessarily pretty, but it works.

### Custom views/urlconfig:
In the compose file, mount a custom `urls.py` and `views/` directory
```yml
# docker_compose.yml
 - ./data/views:/opt/mailman-web/views
 - ./data/urls.py:/opt/mailman-web/urls.py # This overwrites the default urls.py that's there
```
This `urls.py` file contains a custom URL config that refers to the custom views.

### Custom templates/static files
In the compose file, mount directories containing these files, mounted anywhere in the container. Then, create a custom entrypoint that copies these straight into the `postorius` Python package.
```yml
# docker-compose.yml
- ./data/extra/templates:/opt/mailman-extra-templates
- ./data/extra/static:/opt/mailman-extra-static
```

```bash
# custom_entrypoint.sh
#!/bin/bash
cp -r /opt/mailman-extra-templates/* /usr/lib/python*/site-packages/postorius/templates/
cp -r /opt/mailman-extra-static/* /usr/lib/python*/site-packages/postorius/static/

# En dan de container als normaal opstarten
exec docker-entrypoint.sh "$@"
```

A custom Dockerfile is needed to use this entrypoint:
```dockerfile
# Dockerfile-web
FROM docker.io/maxking/postorius:0.4

COPY ./custom_entrypoint.sh /custom_entrypoint.sh
ENTRYPOINT ["/custom_entrypoint.sh"]
CMD ["uwsgi", "--ini", "/opt/mailman-web/uwsgi.ini"]
```

For this to work, the `templates` directory structure has to be like it is in Postorius, i.e.

```
templates/
    account/
    django_mailman3
    postorius/
```

and likewise for the static files:
```
static/
    postorius/
        css/
        js/
        img/
        libs/
```

Note that in these two directories, you only need to put the files that you want to change; `cp -r` will leave any files that you didn't include as Postorius' defaults.
