### ISSUE TITLE
[BUG] rolling release: humanize throws error on startup

### ISSUE THREAD

**Issue by joergmschulz** [maxking/docker-mailman#676]
**Tag/version of Container Images**
Choose from: rolling

On startup, I see:
```
1/site-packages/django/contrib/auth/locale/cs/LC_MESSAGES/django.po” is already compiled and up to date.
mailman-web   | File “/usr/lib/python3.11/site-packages/django/contrib/auth/locale/en/LC_MESSAGES/django.po” is already compiled and up to date.
mailman-web   | File “/usr/lib/python3.11/site-packages/django/contrib/auth/locale/my/LC_MESSAGES/django.po” is already compiled and up to date.
mailman-web   | /opt/mailman-web
mailman-web   | Compressing... Invalid template usersessions/usersession_list.html: 'humanize' is not a registered tag library. Must be one of:
(...)
```

Other than that, login using keycloak works. BUT, the CSS still isn't correct in all places.

**Comment by maxking** [comment]
We need to add humanize to the 'INSTALLED_APPS' and install dependency in the images as well. This is something that django-allauth 0.59.0 requires AFAIK.

**Comment by joergmschulz** [comment]
This has been resolved by the last rolling release. Thank you very much.

**Comment by joergmschulz** [comment]
my bad, didn't see the error line - only the look and feel is available now, the humanize error still shows up
