### ISSUE TITLE
Option to allow only Social Auth for sign ups

### ISSUE THREAD

**Issue by GoliathLabs** [maxking/docker-mailman#677]
Hi, I am currently using the 0.4.6 tag of docker-mailman. I've noticed that there is an option to disable social sign-up or sign-ups in general. In my organisation I need the option to only allow social auth as the social auth goes through our own OpenID Connect provider so only organisation members can sign up. Is there a way to do this? Or is it already implemented in one way or another?

Thanks in advance! :)

**Comment by GoliathLabs** [comment]
It's being worked on (https://gitlab.com/mailman/django-mailman3/-/issues/71 for reference) 🚀

**Comment by maxking** [comment]
It should already be in rolling releases FWIW since the patch was merged a week ago.
