### ISSUE TITLE
site_owner in mailman-extra.cfg

### ISSUE THREAD

**Issue by hartundweich** [maxking/docker-mailman#692]
When putting my site_owner in /opt/mailman/core/mailman-extra.cfg it throws an 500 error in the web frontend when I want to view the details of my mailinglists.
Everything is working fine on my installation except putting site_owner to the configuration.

`[mailman]
site_owner: my@email.com`

is not working for me... but why?

**Comment by maxking** [comment]
When you get 500 in the web frontend, what do you get in the logs for mailman-web?

**Comment by hartundweich** [comment]
I don't know why - i just unmarked the settings which produced to 500 error and now it works? Restarted docker containers as I always did when making configuration changes... very mysterious.
I'll close this issue.
