### ISSUE TITLE
[BUG] docker-mailman-database-1 does not restart when rebooting server

### ISSUE THREAD

**Issue by hartundweich** [maxking/docker-mailman#694]
**Tag/version of Container Images**
maxking/mailman-web:0.4 
maxking/mailman-core:0.4
postgres:11-alpine 

Hello,

I was following the original instructions when setting up mailman in docker images.
I ended with running "docker compose up -d" and everything is running.

When I reboot my server mailman-web and mailman-core containers are started, but postgres container does not automatically start.

How can I fix this?

**Comment by maxking** [comment]
I am not sure why, but we do have `restart: always` for postgres container: https://github.com/maxking/docker-mailman/blob/main/docker-compose-postorius.yaml#L54

This is more of a docker/docker-compose question.

You maybe want to look into container logs and docker logs I guess for hints around why.

**Comment by nicedia** [comment]
> I am not sure why, but we do have `restart: always` for postgres container: https://github.com/maxking/docker-mailman/blob/main/docker-compose-postorius.yaml#L54
> 
> This is more of a docker/docker-compose question.
> 
> You maybe want to look into container logs and docker logs I guess for hints around why.

OK - now I see clearer: added "restart: always" to docker-compose.yaml in the database section as 0.4 is using 11-alpine and not 9.6-alpine
