### ISSUE TITLE
[Security Incident] Bug in referenced Migration Blog https://thomasbandt.com/postgres-docker-major-version-upgrade

### ISSUE THREAD

**Issue by abysso2** [maxking/docker-mailman#702]
Hi all,
if you want to upgrade to mailman 0.5 via docker: this blog shows a docker-compose.yaml with the port section 5432:5432.

if you add these lines to the docker-compose.yaml or docker-compose.override.yaml, your postgres will expose port 5432 to the wild ...

Regards, A.

**Comment by maxking** [comment]
I am not the owner of the blog, the compose file in the repo https://github.com/maxking/docker-mailman/blob/main/docker-compose.yaml#L49 does't do that. Please report the issue to the blog owner.
