### ISSUE TITLE
[BUG] ghcr.io images are not up-to-date

### ISSUE THREAD

**Issue by duck-rh** [maxking/docker-mailman#727]
Quack,

Last version of core and web images in docker is 0.5.2 but on GH it is only 0.4.6, 21 months old, even rolling is more than one year old.
Could you push the images here too?
According to the documentation it's still an official location and I'm really using them.

Regards.
\_o<

**Comment by maxking** [comment]
For some reason, the uploads to ghcr.io seem to be broken. Thanks for bringing this up, i'll take a look at the CI logs to see what's going on.

**Comment by maxking** [comment]
Looks like the github token was expired, i have updated it so it should push out new images. I have also re-triggered pipeline for the latest release so it _should_ publish the new one soon.

**Comment by maxking** [comment]
0.5 and 0.5.2 tags are now available.
