### ISSUE TITLE
Drop privileges and do not run as root

### ISSUE THREAD

**Issue by maxking** [maxking/docker-mailman#8]
Don't run mailman or django as root. Add a new user inside the containers and run as an unprivileged user as a good security practice.

- [x] Core
- [x] Web

**Comment by maxking** [comment]
This is a little tricky than expected. Changing files on mounted volumes can cause problems if we create an unprivileged user inside of the container. 
The best way I can think of is to create a `mailman` user and group on the host os and create the container with those uid/gid maps so that the files have same permissions inside and outside of the containers. 

Not sure how to do this yet, but it looks like something needed soon.

**Comment by maxking** [comment]
SOOOONER!

**Comment by maxking** [comment]
Partially Fixed. Core now run as a non-root user.

**Comment by ishitatsuyuki** [comment]
Permission has long been a problem for Docker, and that's why I keep away from exposing volumes (I always enclose them with named volumes, which is unaccessible due to the executed bit on directory turned off). Anyway, you should `useradd -r` which creates a system user, that makes it harder for a normal human user to shadow the same uid and breaking the privilege.

I think it's nothing wrong to downgrade the privilege, provided that the uid is made safe. The best practice is chown data directory, and then gosu.

**Comment by maxking** [comment]
So I have built these containers so that they can be deployed alongside other applications on a machine and so the real expectations are that the web server and the mail server are on the host and should be able to communicate with the containers.

The core creates the transport maps for postfix and general directories for Exim, if they aren't accessible( read + execute for directories), then it might be a problem. 

Similarly, Django isn't configured to serve the static files and hence need to be exposed to the host and be readable.

I understand that in a perfect container based deployment everything would be in a container, but then you have an option of creating named volumes and sharing them across the containers like you see fit.

The Core container indeed does use a system user IIRC, chowns the data directory and drops down to that privilege. The web container has a pending pull request implementing the same idea, but needs some fixing to get it to work.

**Comment by ishitatsuyuki** [comment]
You don't seem to use a system user in web, and in fact it's shadowing with my main user UID.
Offending line: https://github.com/maxking/docker-mailman/blob/846aa4064f3c4bcc9702e1a09474d030944e1132/web/Dockerfile#L28

I agree with your other points. In fact, I mount the required directory only directly to my webroot, or my postfix chroot.

**Comment by maxking** [comment]
Yeah, the web doesn't do thing properly right now, even though I add a user `mailman` the switch doesn't happen. I have a pending pull request to fix that but it is broken and I need to fix something small.

I am not adding a _system_ user, I have made a note on my PR to change that thanks!

**Comment by maxking** [comment]
UWSGI drops the privileges in mailman-web container, so everything now runs as non-root user.
