### ISSUE TITLE
ERROR: Pool overlaps with other one on this address space

### ISSUE THREAD

**Issue by daamien** [maxking/docker-mailman#85]
Hi

Thanks for this projet ! Installing Mailman3 is tricky and I hope your docker images will help

However I'm getting an error at the early stage:

```
$ docker-compose up
Creating network "dockermailman_mailman" with driver "bridge"
ERROR: Pool overlaps with other one on this address space
```
the host is a regular Linux box:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial

$ uname -a
Linux Hammer 4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

The docker version seems up to date 

```
docker version
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by maxking** [comment]
Are you using `172.19.199.1/24` subnet for something else in your network?

The default compose file provided uses this subnet to create a bridge network and allocates static IPs to the containers.

If this subnet is already in use, you can just change it to a different subnet. You'd have to change 
environment variables and other IPAddresses allocated to each container too.

See the docker-compose.yaml file in the root of the project.

**Comment by daamien** [comment]
Hi !

Thanks for the quick answer 👍 

FTR I am using the docker-compose.yaml file at the root of the project

There's no other docker containers running on the host while I'm doing this test.

I  changed the subnet to 172.20.199.1/24 and modified the other IP adresse accordingly and I still get the same error..

**Comment by maxking** [comment]
Not exactly sure about what is going on but this [thread from docker](https://github.com/moby/moby/issues/21847) might be relevant?

**Comment by daamien** [comment]
Hi !

Actually it seems that a simple `sevirce docker restart` solved the issue. 

Sorry about that. Thanks for your help !

**Comment by Pitastic** [comment]
In case someone else is google'ing here: Even if the containers are down the networks are still persist. With no container running `docker network prune` did it. Guess restarting the service returns the same result.

**Comment by maxking** [comment]
I think the semantics depend on how you actually stop the containers, `docker-compose stop` actually only stops the containers, but, `docker-compose down` stops and remove the containers & network.

https://docs.docker.com/compose/reference/down/
https://docs.docker.com/compose/reference/stop/

**Comment by narehreddythumma** [comment]
**Working when I delete the pool network**

```
docker network ls
NETWORK ID          NAME                          DRIVER              SCOPE  
8518cc751c09        bridge                        bridge              local  
5ebc27713033       pool_network              bridge              local  
25ff8d61d971        host                          host                local  
85c5507b6e64        none                          null                local
```
**remove the pool_network**

`docker network rm pool_network`

**Comment by tmrdurgun** [comment]
İt was about the wrong ip address in compose.yml in my case

**Comment by vanduc1102** [comment]
my case, I have to tun 
```
docker-compose down
docker network prune
```
Then restart Docker service.

**Comment by idreesandroid** [comment]
version: "3"

networks:
  tut07-frontend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.10.1.0/24 
  tut07-backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.10.2.0/23

services:
  tut07-db:
    build: ./db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    networks:
      tut07-backend:
        ipv4_address: 172.10.3.2
    env_file:
      - ./development.env
  tut07-www:
    build: ./www
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html/
    networks:
      tut07-backend:
       ipv4_address: 172.10.2.2
      tut07-frontend:
       ipv4_address: 172.10.1.2
    depends_on:
      - tut07-db
    env_file:
      - ./development.env

#######################################################
above is my docker compose yml file but i got the same error even i have change

**Comment by My-Only-wan** [comment]
docker network prune

**Comment by panchocasanova** [comment]
> In case someone else is google'ing here: Even if the containers are down the networks are still persist. With no container running `docker network prune` did it. Guess restarting the service returns the same result.

it´s worked for me. Thanks you.

**Comment by z3roCoo1** [comment]
> In case someone else is google'ing here: Even if the containers are down the networks are still persist. With no container running `docker network prune` did it. Guess restarting the service returns the same result.

For me `docker network prune` did it whereas `service docker restart1 did not. I'm running the container with macvlan network.

**Comment by briosheje** [comment]
In case you are configuring docker networks with bridge mode and in case you are assigning pool of addresses, make sure each stack has a unique subnet, in my case I had two docker-compose files using the same subnet:

```
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.175.0/24
 ```

In my case, subnet 192.168.175.0/24 was used by two stacks, hence the error.

**Comment by bSushil** [comment]
I also had the same issue. Here is how I fixed it:

1. Listed active networks with ```docker network list```
2. Removed clean_default network with ```docker network rm clean_default```
3. Removed any active container by ```docker container stop (container id)``` and ```docker container prune```
4. Restarted with ```docker-compose up -d```

Doing these fixed the issue for me.

**Comment by KES777** [comment]
@briosheje Hi, Is it possible to configure docker compose to allow stack to reuse subnets? In case I run multiple stacks for one docker-compose.yml file. I name each stack with own `-p` option but want each stack to reuse specified subnet. Is that possible?

**Comment by briosheje** [comment]
> @briosheje Hi, Is it possible to configure docker compose to allow stack to reuse subnets? In case I run multiple stacks for one docker-compose.yml file. I name each stack with own `-p` option but want each stack to reuse specified subnet. Is that possible?

I don't think so, the cleverest is probably to create a network outside the docker-compose first, then use it in docker-compose as "external" (check here for an example: https://stackoverflow.com/questions/38088279/communication-between-multiple-docker-compose-projects), in this way the same address pool is reused (and the same network is used).

**Comment by KES777** [comment]
@briosheje No, I do not want to allow containers to communicate with each other. Those are different testing context thus should be isolated. I want to run them as:
```
docker compose -p proj-${BUILD_NUMBER} up --detach
docker compose -p proj-${BUILD_NUMBER} up --detach
docker compose -p proj-${BUILD_NUMBER} up --detach
```

**Comment by mdakram28** [comment]
> @briosheje No, I do not want to allow containers to communicate with each other. Those are different testing context thus should be isolated. I want to run them as:
> 
> ```
> docker compose -p proj-${BUILD_NUMBER} up --detach
> docker compose -p proj-${BUILD_NUMBER} up --detach
> docker compose -p proj-${BUILD_NUMBER} up --detach
> ```

You could use different subnet for each docker compose app. 

In my case I was creating too many networks. Here's an example of how I fixed it.
```yaml
networks:
  default:
    ipam:
      config:
        - subnet: 172.16.${NETWORK_ID}.0/24
```
And then give a unique `NETWORK_ID` for each run.

```bash
docker compose -p proj-${BUILD_NUMBER} up --detach -e NETWORK_ID=1
docker compose -p proj-${BUILD_NUMBER} up --detach -e NETWORK_ID=2
docker compose -p proj-${BUILD_NUMBER} up --detach -e NETWORK_ID=3
```

If you run out of network ids (0-255) you can create a pool of numbers (0-255) and take a number from the pool for your network_id when you create the network and put it back in the pool when the compose application finishes.

**Comment by williamkoller** [comment]
i added the network without the driver and it worked

**Comment by a7993n** [comment]
Change your subnet 172.* to 192.*

**Comment by horizonvert1027** [comment]
I have create docker container with 
             `docker-compose -f /var/www/klustering-saas/docker-compose.yml up -d` 
the content is here
`version: '3.8'
x-common:
   database: ...
   panel:
       image: ghcr.io/horizonvert1027/klustering:latest
       restart: always
       ports:
           - '3001:80'
       ..................
       networks:
           - exam-bridge-network
networks:
   exam-bridge-network:
       driver: bridge
       ipam:
           config:
               - subnet: 172.20.0.0/16`
successfully, and then I also try one more like this way 
            `docker-compose -f /var/www/klustering-saas/docker-compose.yml up -d`
in here I have updated network from `exam` to `blog` only.
`version: '3.8'
x-common:
   database: ...
   panel:
       image: ghcr.io/horizonvert1027/klustering:latest
       restart: always
       ports:
           - '3001:80'
       ..................
       networks:
           - exam-bridge-network
networks:
   exam-bridge-network:
       driver: bridge
       ipam:
           config:
               - subnet: 172.20.0.0/16`
Then, I have this error `ERROR: Pool overlaps with other one on this address space`, I think I have to change IP address of subnet at docker-compose.yml. 
Question:
- ` where related this IP address?`
- ` when I want to create lots of docker container in aws ubuntu server, How to set IP this IP address of container?`

**Comment by aliuskonte** [comment]
> Change your subnet 172.* to 192.*

Thank you. It halped me

**Comment by jskcnsl** [comment]
Is there any way to change the default bridge subnet 172.19.199.1/24 ? I can't start docker.service after reboot with the same error, so I can't change containers' subnet ...

**Comment by arashlaghaei** [comment]
> > @briosheje Hi, Is it possible to configure docker compose to allow stack to reuse subnets? In case I run multiple stacks for one docker-compose.yml file. I name each stack with own `-p` option but want each stack to reuse specified subnet. Is that possible?
> 
> I don't think so, the cleverest is probably to create a network outside the docker-compose first, then use it in docker-compose as "external" (check here for an example: https://stackoverflow.com/questions/38088279/communication-between-multiple-docker-compose-projects), in this way the same address pool is reused (and the same network is used).

this is not assing to your own network this command tell docker compose go create new network buttt new network with this ip is exists because you created before soo use this code if you created network before:

networks:
  myNetworkCreatedBefore:
    external: true
