### ISSUE TITLE
Cron is running wrongly

### ISSUE THREAD

**Issue by ishitatsuyuki** [maxking/docker-mailman#87]
From the logs, at least "monthly" is running every minute. You're writing cron syntax wrongly.

TLDR: Fill out all values (instead of only one), or they will be replaced with wildcard.

I'm not sure if this is the reason that my archive isn't being generated?

**Comment by maxking** [comment]
Hmmm Archives should be generated regardless. Did you check the logs for any sign of error?

`/opt/mailman/var/logs/mailman.log` inside the core container should have logs related to this error if it exists. I am not sure where is that on your host filesystem as you are using named volumes.

HYPERKITTY_API_KEY env variable could be one of the reason. It has to have same value in both core and web containers.

**Comment by ishitatsuyuki** [comment]
Anyway, I take this. Will open a PR soon.
