### ISSUE TITLE
HYPERKITTY_URL has double defaults

### ISSUE THREAD

**Issue by ishitatsuyuki** [maxking/docker-mailman#88]
https://github.com/maxking/docker-mailman/blob/846aa4064f3c4bcc9702e1a09474d030944e1132/core/assets/run.sh#L43
https://github.com/maxking/docker-mailman/blob/846aa4064f3c4bcc9702e1a09474d030944e1132/core/assets/run.sh#L131

This leads to bad startup defaults, and seemingly generated archive errors for me:

```
HyperKitty failure on http://mailman-web:8000/api/mailman/archive: <h1>Not Found</h1><p>The requested URL /api/mailman/archive was not found on this server.</p> (404)
```

**Comment by ishitatsuyuki** [comment]
I take this.

**Comment by maxking** [comment]
Yeah, looks like my fault. The correct value should be `http://mailman-web:8000/hyperkitty`
