### ISSUE TITLE
Use getaddrinfo() to resolve HyperKitty whitelist

### ISSUE THREAD

**Issue by ishitatsuyuki** [maxking/docker-mailman#92]
https://github.com/maxking/docker-mailman/blob/4373111/web/mailman-web/settings.py#L62
https://docs.python.org/3/library/socket.html#socket.getaddrinfo

Both IPv4 and IPv6 should be appended for failsafe. The hardcoded IP can be removed.

**Comment by maxking** [comment]
The variable itself is probably just supposed to be either the address or hostname of the `mailman-web` container. I am not sure if we can set both IPv4 and IPv6 address here.

Maybe open an issue with Hyperkitty?

**Comment by ishitatsuyuki** [comment]
I'm not sure I understand what you say. The list is expected to be the IP of **core**. And it's IP only, as HyperKitty doesn't do reverse lookup just for a whitelist and it shouldn't either.

**Comment by maxking** [comment]
@ishitatsuyuki Ah, I thought it was a single var and not a list. My bad.
