### ISSUE TITLE
Full text index permission error

### ISSUE THREAD

**Issue by ishitatsuyuki** [maxking/docker-mailman#96]
https://github.com/maxking/docker-mailman/blob/43731112e7b69bac6038875864a68d31703b8348/web/mailman-web/settings.py#L301

```
IOError: The path to your Whoosh index '/opt/mailman-web/fulltext_index' is not writable for the current user/group.
```

**Comment by maxking** [comment]
I wonder why would this happen, the mailman-web container basically runs as root. I will investigate more.

**Comment by ishitatsuyuki** [comment]
Uh, if that matters, I ran a few Django management jobs in the container as root.

**Comment by maxking** [comment]
Even then, as long as you don't drop the privileges, root should not have problems writing anywhere inside the container. `/opt/mailman-web/` is inside the container and not even on a shared volume.

If you can reproduce this error, can you also check the user/group for which this error occurs?

**Comment by ishitatsuyuki** [comment]
```
root@mailman-web:/opt/mailman-web# stat .                             
File: ‘.’
Size: 4096            Blocks: 8          IO Block: 4096   directory
Device: fd03h/64771d    Inode: 408226      Links: 2
Access: (0755/drwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2017-07-26 11:52:35.730255628 +0000
Modify: 2017-07-26 11:52:34.738255603 +0000
Change: 2017-07-26 11:52:34.738255603 +0000
Birth: -
```

All `python` process are running as UID 1000.

**Comment by maxking** [comment]
I think I need some bigger ram for my own head, I completely forgot that in mailman-web container, uwsgi drops privileges and so there isn't any need to actually use gosu, unless we take into account the bugs in uwsgi itself.

So then yes, if you run anything as root and permissions of fulltext_search changes, it might be possible to get this Error.

**Comment by ishitatsuyuki** [comment]
Actually no. There's no such file there from the beginning, as the directory has the write bit off.

**Comment by maxking** [comment]
It should not be there anyway, I didn't change the default settings. I think the best idea would be to change the path to `/opt/mailman-web-data/fulltext_index`. That directory should be writable by the mailman user.

**Comment by ishitatsuyuki** [comment]
Yup. That's what I imagined from the beginning.

**Comment by maxking** [comment]
I already have opened a new issue for that #98

**Comment by ishitatsuyuki** [comment]
Duplicate of #98
