### ISSUE TITLE
Vulnerability: SECRET_KEY is default

### ISSUE THREAD

**Issue by ishitatsuyuki** [maxking/docker-mailman#99]
https://github.com/maxking/docker-mailman/blob/4373111/web/mailman-web/settings.py#L35

Proposed solution: remove this line and force any vulnerable users updated to set it.

**Comment by maxking** [comment]
Setting via Environment variable should also be possible.

**Comment by maxking** [comment]
But, I am not sure how to make that option available to flexibility to define it in either settings_local.py or Environment variable.

Will probably mandate using the Environment variable.
